import 'dart:convert';
import 'dart:io';

void main() {
  final newKeys = {
    'en': {
      'myProducts': 'My Products',
      'addProduct': 'Add Product',
      'editProduct': 'Edit Product',
      'deleteProduct': 'Delete Product',
      'productName': 'Product Name',
      'category': 'Category',
      'description': 'Description',
      'quality': 'Quality',
      'price': 'Price',
      'quantity': 'Quantity',
      'unit': 'Unit',
      'location': 'Location',
      'harvestDate': 'Harvest Date',
      'available': 'Available',
      'unavailable': 'Unavailable',
      'saveProduct': 'Save Product',
      'updateProduct': 'Update Product',
      'cancel': 'Cancel',
      'delete': 'Delete',
      'confirm': 'Confirm',
      'noProducts': 'No Products',
      'productAdded': 'Product Added',
      'productUpdated': 'Product Updated',
      'productDeleted': 'Product Deleted',
      'requiredField': 'Required Field',
      'invalidPrice': 'Invalid Price',
      'confirmDelete': 'Confirm Delete',
      'confirmDeleteMsg': 'Are you sure you want to delete this product?',
      'uploadImageLabel': 'Image placeholder (Future)',
    },
    'hi': {
      'myProducts': 'मेरे उत्पाद',
      'addProduct': 'उत्पाद जोड़ें',
      'editProduct': 'उत्पाद संपादित करें',
      'deleteProduct': 'उत्पाद हटाएं',
      'productName': 'उत्पाद का नाम',
      'category': 'श्रेणी',
      'description': 'विवरण',
      'quality': 'गुणवत्ता',
      'price': 'मूल्य',
      'quantity': 'मात्रा',
      'unit': 'इकाई',
      'location': 'स्थान',
      'harvestDate': 'फसल की तारीख',
      'available': 'उपलब्ध',
      'unavailable': 'अनुपलब्ध',
      'saveProduct': 'उत्पाद सहेजें',
      'updateProduct': 'उत्पाद अपडेट करें',
      'cancel': 'रद्द करें',
      'delete': 'हटाएं',
      'confirm': 'पुष्टि करें',
      'noProducts': 'कोई उत्पाद नहीं',
      'productAdded': 'उत्पाद जोड़ा गया',
      'productUpdated': 'उत्पाद अपडेट किया गया',
      'productDeleted': 'उत्पाद हटा दिया गया',
      'requiredField': 'आवश्यक फ़ील्ड',
      'invalidPrice': 'अमान्य मूल्य',
      'confirmDelete': 'हटाने की पुष्टि करें',
      'confirmDeleteMsg': 'क्या आप वाकई इस उत्पाद को हटाना चाहते हैं?',
      'uploadImageLabel': 'छवि प्लेसहोल्डर (भविष्य)',
    },
    'bn': {
      'myProducts': 'আমার পণ্য',
      'addProduct': 'পণ্য যোগ করুন',
      'editProduct': 'পণ্য সম্পাদনা করুন',
      'deleteProduct': 'পণ্য মুছুন',
      'productName': 'পণ্যের নাম',
      'category': 'বিভাগ',
      'description': 'বিবরণ',
      'quality': 'মান',
      'price': 'দাম',
      'quantity': 'পরিমাণ',
      'unit': 'ইউনিট',
      'location': 'অবস্থান',
      'harvestDate': 'ফসল তোলার তারিখ',
      'available': 'পাওয়া যায়',
      'unavailable': 'পাওয়া যায় না',
      'saveProduct': 'পণ্য সংরক্ষণ করুন',
      'updateProduct': 'পণ্য আপডেট করুন',
      'cancel': 'বাতিল করুন',
      'delete': 'মুছুন',
      'confirm': 'নিশ্চিত করুন',
      'noProducts': 'কোনো পণ্য নেই',
      'productAdded': 'পণ্য যোগ করা হয়েছে',
      'productUpdated': 'পণ্য আপডেট করা হয়েছে',
      'productDeleted': 'পণ্য মুছে ফেলা হয়েছে',
      'requiredField': 'প্রয়োজনীয় ক্ষেত্র',
      'invalidPrice': 'অবৈধ দাম',
      'confirmDelete': 'মুছে ফেলা নিশ্চিত করুন',
      'confirmDeleteMsg': 'আপনি কি নিশ্চিত যে আপনি এই পণ্যটি মুছতে চান?',
      'uploadImageLabel': 'ইমেজ প্লেসহোল্ডার (ভবিষ্যত)',
    },
    'mr': {
      'myProducts': 'माझी उत्पादने',
      'addProduct': 'उत्पादन जोडा',
      'editProduct': 'उत्पादन संपादित करा',
      'deleteProduct': 'उत्पादन हटवा',
      'productName': 'उत्पादनाचे नाव',
      'category': 'श्रेणी',
      'description': 'वर्णन',
      'quality': 'गुणवत्ता',
      'price': 'किंमत',
      'quantity': 'प्रमाण',
      'unit': 'एकक',
      'location': 'स्थान',
      'harvestDate': 'कापणीची तारीख',
      'available': 'उपलब्ध',
      'unavailable': 'अनुपलब्ध',
      'saveProduct': 'उत्पादन जतन करा',
      'updateProduct': 'उत्पादन अद्यतनित करा',
      'cancel': 'रद्द करा',
      'delete': 'हटवा',
      'confirm': 'पुष्टी करा',
      'noProducts': 'कोणतीही उत्पादने नाहीत',
      'productAdded': 'उत्पादन जोडले',
      'productUpdated': 'उत्पादन अद्यतनित केले',
      'productDeleted': 'उत्पादन हटवले',
      'requiredField': 'आवश्यक फील्ड',
      'invalidPrice': 'अवैध किंमत',
      'confirmDelete': 'हटवण्याची पुष्टी करा',
      'confirmDeleteMsg': 'तुम्हाला नक्की हे उत्पादन हटवायचे आहे का?',
      'uploadImageLabel': 'प्रतिमा प्लेसहोल्डर (भविष्य)',
    },
    'te': {
      'myProducts': 'నా ఉత్పత్తులు',
      'addProduct': 'ఉత్పత్తిని జోడించండి',
      'editProduct': 'ఉత్పత్తిని సవరించండి',
      'deleteProduct': 'ఉత్పత్తిని తొలగించండి',
      'productName': 'ఉత్పత్తి పేరు',
      'category': 'వర్గం',
      'description': 'వివరణ',
      'quality': 'నాణ్యత',
      'price': 'ధర',
      'quantity': 'పరిమాణం',
      'unit': 'యూనిట్',
      'location': 'స్థానం',
      'harvestDate': 'కోత తేదీ',
      'available': 'అందుబాటులో ఉంది',
      'unavailable': 'అందుబాటులో లేదు',
      'saveProduct': 'ఉత్పత్తిని సేవ్ చేయండి',
      'updateProduct': 'ఉత్పత్తిని నవీకరించండి',
      'cancel': 'రద్దు చేయండి',
      'delete': 'తొలగించండి',
      'confirm': 'నిర్ధారించండి',
      'noProducts': 'ఉత్పత్తులు లేవు',
      'productAdded': 'ఉత్పత్తి జోడించబడింది',
      'productUpdated': 'ఉత్పత్తి నవీకరించబడింది',
      'productDeleted': 'ఉత్పత్తి తొలగించబడింది',
      'requiredField': 'అవసరమైన ఫీల్డ్',
      'invalidPrice': 'చెల్లని ధర',
      'confirmDelete': 'తొలగింపును నిర్ధారించండి',
      'confirmDeleteMsg': 'మీరు ఖచ్చితంగా ఈ ఉత్పత్తిని తొలగించాలనుకుంటున్నారా?',
      'uploadImageLabel': 'చిత్రం ప్లేస్‌హోల్డర్ (భవిష్యత్తు)',
    },
    'ta': {
      'myProducts': 'எனது தயாரிப்புகள்',
      'addProduct': 'தயாரிப்பைச் சேர்',
      'editProduct': 'தயாரிப்பைத் திருத்து',
      'deleteProduct': 'தயாரிப்பை நீக்கு',
      'productName': 'தயாரிப்பு பெயர்',
      'category': 'வகை',
      'description': 'விளக்கம்',
      'quality': 'தரம்',
      'price': 'விலை',
      'quantity': 'அளவு',
      'unit': 'அலகு',
      'location': 'இடம்',
      'harvestDate': 'அறுவடை தேதி',
      'available': 'கிடைக்கிறது',
      'unavailable': 'கிடைக்கவில்லை',
      'saveProduct': 'தயாரிப்பைச் சேமி',
      'updateProduct': 'தயாரிப்பைப் புதுப்பி',
      'cancel': 'ரத்துசெய்',
      'delete': 'நீக்கு',
      'confirm': 'உறுதிப்படுத்து',
      'noProducts': 'தயாரிப்புகள் இல்லை',
      'productAdded': 'தயாரிப்பு சேர்க்கப்பட்டது',
      'productUpdated': 'தயாரிப்பு புதுப்பிக்கப்பட்டது',
      'productDeleted': 'தயாரிப்பு நீக்கப்பட்டது',
      'requiredField': 'தேவையான புலம்',
      'invalidPrice': 'தவறான விலை',
      'confirmDelete': 'நீக்குதலை உறுதிப்படுத்துக',
      'confirmDeleteMsg': 'இந்த தயாரிப்பை நிச்சயமாக நீக்க வேண்டுமா?',
      'uploadImageLabel': 'படம் ஒதுக்கிடம் (எதிர்காலம்)',
    },
    'gu': {
      'myProducts': 'મારા ઉત્પાદનો',
      'addProduct': 'ઉત્પાદન ઉમેરો',
      'editProduct': 'ઉત્પાદન સંપાદિત કરો',
      'deleteProduct': 'ઉત્પાદન કાઢી નાખો',
      'productName': 'ઉત્પાદનનું નામ',
      'category': 'શ્રેણી',
      'description': 'વર્ણન',
      'quality': 'ગુણવત્તા',
      'price': 'કિંમત',
      'quantity': 'જથ્થો',
      'unit': 'એકમ',
      'location': 'સ્થાન',
      'harvestDate': 'લણણીની તારીખ',
      'available': 'ઉપલબ્ધ',
      'unavailable': 'અનુપલબ્ધ',
      'saveProduct': 'ઉત્પાદન સાચવો',
      'updateProduct': 'ઉત્પાદન અપડેટ કરો',
      'cancel': 'રદ કરો',
      'delete': 'કાઢી નાખો',
      'confirm': 'પુષ્ટિ કરો',
      'noProducts': 'કોઈ ઉત્પાદનો નથી',
      'productAdded': 'ઉત્પાદન ઉમેર્યું',
      'productUpdated': 'ઉત્પાદન અપડેટ કર્યું',
      'productDeleted': 'ઉત્પાદન કાઢી નાખ્યું',
      'requiredField': 'જરૂરી ક્ષેત્ર',
      'invalidPrice': 'અમાન્ય કિંમત',
      'confirmDelete': 'કાઢી નાખવાની પુષ્ટિ કરો',
      'confirmDeleteMsg': 'શું તમે ખરેખર આ ઉત્પાદન કાઢી નાખવા માંગો છો?',
      'uploadImageLabel': 'છબી પ્લેસહોલ્ડર (ભવિષ્ય)',
    },
    'kn': {
      'myProducts': 'ನನ್ನ ಉತ್ಪನ್ನಗಳು',
      'addProduct': 'ಉತ್ಪನ್ನ ಸೇರಿಸಿ',
      'editProduct': 'ಉತ್ಪನ್ನ ಸಂಪಾದಿಸಿ',
      'deleteProduct': 'ಉತ್ಪನ್ನ ಅಳಿಸಿ',
      'productName': 'ಉತ್ಪನ್ನದ ಹೆಸರು',
      'category': 'ವರ್ಗ',
      'description': 'ವಿವರಣೆ',
      'quality': 'ಗುಣಮಟ್ಟ',
      'price': 'ಬೆಲೆ',
      'quantity': 'ಪ್ರಮಾಣ',
      'unit': 'ಘಟಕ',
      'location': 'ಸ್ಥಳ',
      'harvestDate': 'ಕೊಯ್ಲು ದಿನಾಂಕ',
      'available': 'ಲಭ್ಯವಿದೆ',
      'unavailable': 'ಲಭ್ಯವಿಲ್ಲ',
      'saveProduct': 'ಉತ್ಪನ್ನ ಉಳಿಸಿ',
      'updateProduct': 'ಉತ್ಪನ್ನ ನವೀಕರಿಸಿ',
      'cancel': 'ರದ್ದುಮಾಡಿ',
      'delete': 'ಅಳಿಸಿ',
      'confirm': 'ಖಚಿತಪಡಿಸಿ',
      'noProducts': 'ಯಾವುದೇ ಉತ್ಪನ್ನಗಳಿಲ್ಲ',
      'productAdded': 'ಉತ್ಪನ್ನ ಸೇರಿಸಲಾಗಿದೆ',
      'productUpdated': 'ಉತ್ಪನ್ನ ನವೀಕರಿಸಲಾಗಿದೆ',
      'productDeleted': 'ಉತ್ಪನ್ನ ಅಳಿಸಲಾಗಿದೆ',
      'requiredField': 'ಅಗತ್ಯವಿರುವ ಕ್ಷೇತ್ರ',
      'invalidPrice': 'ಅಮಾನ್ಯ ಬೆಲೆ',
      'confirmDelete': 'ಅಳಿಸುವಿಕೆಯನ್ನು ಖಚಿತಪಡಿಸಿ',
      'confirmDeleteMsg': 'ಈ ಉತ್ಪನ್ನವನ್ನು ಅಳಿಸಲು ನೀವು ಖಚಿತವಾಗಿ ಬಯಸುವಿರಾ?',
      'uploadImageLabel': 'ಚಿತ್ರ ಪ್ಲೇಸ್‌ಹೋಲ್ಡರ್ (ಭವಿಷ್ಯ)',
    },
    'ml': {
      'myProducts': 'എൻ്റെ ഉൽപ്പന്നങ്ങൾ',
      'addProduct': 'ഉൽപ്പന്നം ചേർക്കുക',
      'editProduct': 'ഉൽപ്പന്നം എഡിറ്റ് ചെയ്യുക',
      'deleteProduct': 'ഉൽപ്പന്നം ഇല്ലാതാക്കുക',
      'productName': 'ഉൽപ്പന്നത്തിൻ്റെ പേര്',
      'category': 'വിഭാഗം',
      'description': 'വിവരണം',
      'quality': 'ഗുണമേന്മ',
      'price': 'വില',
      'quantity': 'അളവ്',
      'unit': 'യൂണിറ്റ്',
      'location': 'സ്ഥലം',
      'harvestDate': 'വിളവെടുപ്പ് തീയതി',
      'available': 'ലഭ്യമാണ്',
      'unavailable': 'ലഭ്യമല്ല',
      'saveProduct': 'ഉൽപ്പന്നം സംരക്ഷിക്കുക',
      'updateProduct': 'ഉൽപ്പന്നം അപ്ഡേറ്റ് ചെയ്യുക',
      'cancel': 'റദ്ദാക്കുക',
      'delete': 'ഇല്ലാതാക്കുക',
      'confirm': 'സ്ഥിരീകരിക്കുക',
      'noProducts': 'ഉൽപ്പന്നങ്ങളൊന്നുമില്ല',
      'productAdded': 'ഉൽപ്പന്നം ചേർത്തു',
      'productUpdated': 'ഉൽപ്പന്നം അപ്ഡേറ്റ് ചെയ്തു',
      'productDeleted': 'ഉൽപ്പന്നം ഇല്ലാതാക്കി',
      'requiredField': 'ആവശ്യമായ ഫീൽഡ്',
      'invalidPrice': 'അസാധുവായ വില',
      'confirmDelete': 'ഇല്ലാതാക്കൽ സ്ഥിരീകരിക്കുക',
      'confirmDeleteMsg': 'ഈ ഉൽപ്പന്നം ഇല്ലാതാക്കണമെന്ന് നിങ്ങൾക്ക് ഉറപ്പാണോ?',
      'uploadImageLabel': 'ഇമേജ് പ്ലേസ്ഹോൾഡർ (ഭാവി)',
    },
    'pa': {
      'myProducts': 'ਮੇਰੇ ਉਤਪਾਦ',
      'addProduct': 'ਉਤਪਾਦ ਸ਼ਾਮਲ ਕਰੋ',
      'editProduct': 'ਉਤਪਾਦ ਸੰਪਾਦਿਤ ਕਰੋ',
      'deleteProduct': 'ਉਤਪਾਦ ਮਿਟਾਓ',
      'productName': 'ਉਤਪਾਦ ਦਾ ਨਾਮ',
      'category': 'ਸ਼੍ਰੇਣੀ',
      'description': 'ਵਰਣਨ',
      'quality': 'ਗੁਣਵੱਤਾ',
      'price': 'ਕੀਮਤ',
      'quantity': 'ਮਾਤਰਾ',
      'unit': 'ਇਕਾਈ',
      'location': 'ਸਥਾਨ',
      'harvestDate': 'ਵਾਢੀ ਦੀ ਤਾਰੀਖ',
      'available': 'ਉਪਲਬਧ',
      'unavailable': 'ਉਪਲਬਧ ਨਹੀਂ',
      'saveProduct': 'ਉਤਪਾਦ ਸੇਵ ਕਰੋ',
      'updateProduct': 'ਉਤਪਾਦ ਅੱਪਡੇਟ ਕਰੋ',
      'cancel': 'ਰੱਦ ਕਰੋ',
      'delete': 'ਮਿਟਾਓ',
      'confirm': 'ਪੁਸ਼ਟੀ ਕਰੋ',
      'noProducts': 'ਕੋਈ ਉਤਪਾਦ ਨਹੀਂ',
      'productAdded': 'ਉਤਪਾਦ ਸ਼ਾਮਲ ਕੀਤਾ ਗਿਆ',
      'productUpdated': 'ਉਤਪਾਦ ਅੱਪਡੇਟ ਕੀਤਾ ਗਿਆ',
      'productDeleted': 'ਉਤਪਾਦ ਮਿਟਾਇਆ ਗਿਆ',
      'requiredField': 'ਲੋੜੀਂਦਾ ਖੇਤਰ',
      'invalidPrice': 'ਅਵੈਧ ਕੀਮਤ',
      'confirmDelete': 'ਮਿਟਾਉਣ ਦੀ ਪੁਸ਼ਟੀ ਕਰੋ',
      'confirmDeleteMsg':
          'ਕੀ ਤੁਸੀਂ ਯਕੀਨੀ ਤੌਰ \'ਤੇ ਇਸ ਉਤਪਾਦ ਨੂੰ ਮਿਟਾਉਣਾ ਚਾਹੁੰਦੇ ਹੋ?',
      'uploadImageLabel': 'ਚਿੱਤਰ ਪਲੇਸਹੋਲਡਰ (ਭਵਿੱਖ)',
    },
    'or': {
      'myProducts': 'ମୋର ଉତ୍ପାଦଗୁଡ଼ିକ',
      'addProduct': 'ଉତ୍ପାଦ ଯୋଡନ୍ତୁ',
      'editProduct': 'ଉତ୍ପାଦ ସମ୍ପାଦନ କରନ୍ତୁ',
      'deleteProduct': 'ଉତ୍ପାଦ ବିଲୋପ କରନ୍ତୁ',
      'productName': 'ଉତ୍ପାଦର ନାମ',
      'category': 'ବର୍ଗ',
      'description': 'ବିବରଣୀ',
      'quality': 'ଗୁଣବତ୍ତା',
      'price': 'ମୂଲ୍ୟ',
      'quantity': 'ପରିମାଣ',
      'unit': 'ଏକକ',
      'location': 'ସ୍ଥାନ',
      'harvestDate': 'ଅମଳ ତାରିଖ',
      'available': 'ଉପଲବ୍ଧ',
      'unavailable': 'ଅନୁପଲବ୍ଧ',
      'saveProduct': 'ଉତ୍ପାଦ ସେଭ୍ କରନ୍ତୁ',
      'updateProduct': 'ଉତ୍ପାଦ ଅପଡେଟ୍ କରନ୍ତୁ',
      'cancel': 'ବାତିଲ୍ କରନ୍ତୁ',
      'delete': 'ବିଲୋପ କରନ୍ତୁ',
      'confirm': 'ନିଶ୍ଚିତ କରନ୍ତୁ',
      'noProducts': 'କୌଣସି ଉତ୍ପାଦ ନାହିଁ',
      'productAdded': 'ଉତ୍ପାଦ ଯୋଡାଗଲା',
      'productUpdated': 'ଉତ୍ପାଦ ଅପଡେଟ୍ ହେଲା',
      'productDeleted': 'ଉତ୍ପାଦ ବିଲୋପ କରାଗଲା',
      'requiredField': 'ଆବଶ୍ୟକ କ୍ଷେତ୍ର',
      'invalidPrice': 'ଅବୈଧ ମୂଲ୍ୟ',
      'confirmDelete': 'ବିଲୋପ କରିବା ନିଶ୍ଚିତ କରନ୍ତୁ',
      'confirmDeleteMsg':
          'ଆପଣ ନିଶ୍ଚିତ କି ଆପଣ ଏହି ଉତ୍ପାଦଟି ବିଲୋପ କରିବାକୁ ଚାହୁଁଛନ୍ତି?',
      'uploadImageLabel': 'ପ୍ରତିଛବି ପ୍ଲେସହୋଲ୍ଡର (ଭବିଷ୍ୟତ)',
    },
    'as': {
      'myProducts': 'মোৰ সামগ্ৰীসমূহ',
      'addProduct': 'সামগ্ৰী যোগ কৰক',
      'editProduct': 'সামগ্ৰী সম্পাদনা কৰক',
      'deleteProduct': 'সামগ্ৰী মচি পেলাওক',
      'productName': 'সামগ্ৰীৰ নাম',
      'category': 'শ্ৰেণী',
      'description': 'বিৱৰণ',
      'quality': 'গুণমান',
      'price': 'দাম',
      'quantity': 'পৰিমাণ',
      'unit': 'একক',
      'location': 'স্থান',
      'harvestDate': 'খেতি চপোৱা তাৰিখ',
      'available': 'উপলব্ধ',
      'unavailable': 'উপলব্ধ নহয়',
      'saveProduct': 'সামগ্ৰী ছেভ কৰক',
      'updateProduct': 'সামগ্ৰী আপডেট কৰক',
      'cancel': 'বাতিল কৰক',
      'delete': 'মচি পেলাওক',
      'confirm': 'নিশ্চিত কৰক',
      'noProducts': 'কোনো সামগ্ৰী নাই',
      'productAdded': 'সামগ্ৰী যোগ কৰা হ\'ল',
      'productUpdated': 'সামগ্ৰী আপডেট কৰা হ\'ল',
      'productDeleted': 'সামগ্ৰী মচি পেলোৱা হ\'ল',
      'requiredField': 'প্ৰয়োজনীয় ক্ষেত্ৰ',
      'invalidPrice': 'অবৈধ দাম',
      'confirmDelete': 'মচি পেলোৱা নিশ্চিত কৰক',
      'confirmDeleteMsg':
          'আপুনি নিশ্চিতনে যে আপুনি এই সামগ্ৰীটো মচি পেলাব বিচাৰে?',
      'uploadImageLabel': 'ছবিৰ ঠাই (ভৱিষ্যত)',
    },
  };

  for (final entry in newKeys.entries) {
    final file = File('lib/l10n/app_${entry.key}.arb');
    if (file.existsSync()) {
      final content = file.readAsStringSync();
      final Map<String, dynamic> json = jsonDecode(content);
      // Remove overlapping keys if they exist from my previous turn, and then add
      json.remove('myProducts');
      json.addAll(entry.value as Map<String, dynamic>);
      file.writeAsStringSync(
        '{\n' +
            json.entries.map((e) => '  "${e.key}": "${e.value}"').join(',\n') +
            '\n}\n',
      );
    }
  }
}
