import json
import os

langs = ['hi', 'bn', 'mr', 'gu', 'ta', 'te', 'kn', 'ml', 'or', 'pa', 'as']

# Base dictionary of translations for the essential farmer marketplace fields
translations = {
    'wheat': {'hi': 'गेहूँ (Wheat)', 'bn': 'গম (Wheat)', 'mr': 'गहू (Wheat)', 'gu': 'ઘઉં (Wheat)', 'ta': 'கோதுமை (Wheat)', 'te': 'గోధుమలు (Wheat)', 'kn': 'ಗೋದಿಯು (Wheat)', 'ml': 'ഗോതമ്പ് (Wheat)', 'or': 'ଗହମ (Wheat)', 'pa': 'ਕਣਕ (Wheat)', 'as': 'ঘেঁহু (Wheat)'},
    'rice': {'hi': 'चावल (Rice)', 'bn': 'চাল (Rice)', 'mr': 'तांदूळ (Rice)', 'gu': 'ચોખા (Rice)', 'ta': 'அரிசி (Rice)', 'te': 'బియ్యం (Rice)', 'kn': 'ಅಕ್ಕಿ (Rice)', 'ml': 'അരി (Rice)', 'or': 'ଚାଉଳ (Rice)', 'pa': 'ਚੌਲ (Rice)', 'as': 'চাউল (Rice)'},
    'potato': {'hi': 'आलू (Potato)', 'bn': 'আলু (Potato)', 'mr': 'बटाटा (Potato)', 'gu': 'બટાકા (Potato)', 'ta': 'உருளைக்கிழங்கு (Potato)', 'te': 'బంగాళాదుంప (Potato)', 'kn': 'ಆಲೂಗಡ್ಡೆ (Potato)', 'ml': 'ഉരുളക്കിഴങ്ങ് (Potato)', 'or': 'ଆଳୁ (Potato)', 'pa': 'ਆਲੂ (Potato)', 'as': 'আলু (Potato)'},
    'onion': {'hi': 'प्याज़ (Onion)', 'bn': 'পেঁয়াজ (Onion)', 'mr': 'कांदा (Onion)', 'gu': 'ડુંગળી (Onion)', 'ta': 'வெங்காயம் (Onion)', 'te': 'ఉల్లిపాయ (Onion)', 'kn': 'ಈರುಳ್ಳಿ (Onion)', 'ml': 'ഉള്ളി (Onion)', 'or': 'ପିଆଜ (Onion)', 'pa': 'ਪਿਆਜ਼ (Onion)', 'as': 'পিয়াঁজ (Onion)'},
    'tomato': {'hi': 'टमाटर (Tomato)', 'bn': 'টমেটো (Tomato)', 'mr': 'टोमॅटो (Tomato)', 'gu': 'ટામેટા (Tomato)', 'ta': 'தக்காளி (Tomato)', 'te': 'టమోటా (Tomato)', 'kn': 'ಟೊಮೆಟೊ (Tomato)', 'ml': 'തക്കാളി (Tomato)', 'or': 'ଟମାଟୋ (Tomato)', 'pa': 'ਟਮਾਟਰ (Tomato)', 'as': 'বিলাহী (Tomato)'},
    'vegetables': {'hi': 'सब्ज़ियाँ (Vegetables)', 'bn': 'সবজি (Vegetables)', 'mr': 'भाज्या (Vegetables)', 'gu': 'શાકભાજી (Vegetables)', 'ta': 'காய்கறிகள் (Vegetables)', 'te': 'కూరగాయలు (Vegetables)', 'kn': 'ತರಕಾರಿಗಳು (Vegetables)', 'ml': 'പച്ചക്കറികൾ (Vegetables)', 'or': 'ପନିପରିବା (Vegetables)', 'pa': 'ਸਬਜ਼ੀਆਂ (Vegetables)', 'as': 'পাচলি (Vegetables)'},
    'fruits': {'hi': 'फल (Fruits)', 'bn': 'ফল (Fruits)', 'mr': 'फळे (Fruits)', 'gu': 'ફળો (Fruits)', 'ta': 'பழங்கள் (Fruits)', 'te': 'పండ్లు (Fruits)', 'kn': 'ಹಣ್ಣುಗಳು (Fruits)', 'ml': 'പഴങ്ങൾ (Fruits)', 'or': 'ଫଳ (Fruits)', 'pa': 'ਫਲ (Fruits)', 'as': 'ফল (Fruits)'},
    'pulses': {'hi': 'दालें (Pulses)', 'bn': 'ডাল (Pulses)', 'mr': 'डाळी (Pulses)', 'gu': 'કઠોળ (Pulses)', 'ta': 'பருப்புகள் (Pulses)', 'te': 'పప్పులు (Pulses)', 'kn': 'ಕಾಳುಗಳು (Pulses)', 'ml': 'പയറുവർഗ്ഗങ്ങൾ (Pulses)', 'or': 'ଡାଲି (Pulses)', 'pa': 'ਦਾਲਾਂ (Pulses)', 'as': 'দাইল (Pulses)'},
    'spices': {'hi': 'मसाले (Spices)', 'bn': 'মশলা (Spices)', 'mr': 'मसाले (Spices)', 'gu': 'મસાલા (Spices)', 'ta': 'மசாலா (Spices)', 'te': 'సుగంధ ద్రవ్యాలు (Spices)', 'kn': 'ಮಸಾಲೆಗಳು (Spices)', 'ml': 'സുഗന്ധവ്യഞ്ജനങ്ങൾ (Spices)', 'or': 'ମସଲା (Spices)', 'pa': 'ਮਸਾਲੇ (Spices)', 'as': 'মছলা (Spices)'},
    'other': {'hi': 'अन्य (Other)', 'bn': 'অন্যান্য (Other)', 'mr': 'इतर (Other)', 'gu': 'અન્ય (Other)', 'ta': 'மற்றவை (Other)', 'te': 'ఇతర (Other)', 'kn': 'ಇತರೆ (Other)', 'ml': 'മറ്റുള്ളവ (Other)', 'or': 'ଅନ୍ୟାନ୍ୟ (Other)', 'pa': 'ਹੋਰ (Other)', 'as': 'অন্যান্য (Other)'},
    
    'bulkRequirements': {'hi': 'थोक आवश्यकताएँ (Bulk Requirements)', 'bn': 'বাল্ক প্রয়োজনীয়তা (Bulk Requirements)', 'mr': 'मोठ्या प्रमाणात आवश्यकता (Bulk Requirements)', 'gu': 'જથ્થાબંધ જરૂરિયાતો (Bulk Requirements)', 'ta': 'மொத்த தேவைகள் (Bulk Requirements)', 'te': 'టోకు అవసరాలు (Bulk Requirements)', 'kn': 'ಬೃಹತ್ ಅಗತ್ಯತೆಗಳು (Bulk Requirements)', 'ml': 'മൊത്തത്തിലുള്ള ആവശ്യകതകൾ (Bulk Requirements)', 'or': 'ବହୁଳ ଆବଶ୍ୟକତା (Bulk Requirements)', 'pa': 'ਥੋਕ ਲੋੜਾਂ (Bulk Requirements)', 'as': 'বাল্ক প্ৰয়োজনীয়তা (Bulk Requirements)'},
    'myOffers': {'hi': 'मेरे प्रस्ताव (My Offers)', 'bn': 'আমার অফার (My Offers)', 'mr': 'माझ्या ऑफर (My Offers)', 'gu': 'મારી ઑફર્સ (My Offers)', 'ta': 'எனது சலுகைகள் (My Offers)', 'te': 'నా ఆఫర్లు (My Offers)', 'kn': 'ನನ್ನ ಕೊಡುಗೆಗಳು (My Offers)', 'ml': 'എന്റെ ഓഫറുകൾ (My Offers)', 'or': 'ମୋର ଅଫର୍ (My Offers)', 'pa': 'ਮੇਰੀਆਂ ਪੇਸ਼ਕਸ਼ਾਂ (My Offers)', 'as': 'মোৰ প্ৰস্তাৱসমূহ (My Offers)'},
    
    'accepted': {'hi': 'स्वीकृत', 'bn': 'গৃহীত', 'mr': 'स्वीकृत', 'gu': 'સ્વીકાર્ય', 'ta': 'ஏற்றுக்கொள்ளப்பட்டது', 'te': 'ఆమోదించబడింది', 'kn': 'ಅಂಗೀಕರಿಸಲಾಗಿದೆ', 'ml': 'സ്വീകരിച്ചു', 'or': 'ଗୃହୀତ', 'pa': 'ਮਨਜ਼ੂਰ', 'as': 'গ্ৰহণ কৰা হৈছে'},
    'acceptedQuantity': {'hi': 'स्वीकृत मात्रा', 'bn': 'গৃহীত পরিমাণ', 'mr': 'स्वीकृत प्रमाण', 'gu': 'સ્વીકૃત જથ્થો', 'ta': 'ஏற்றுக்கொள்ளப்பட்ட அளவு', 'te': 'ఆమోదించబడిన పరిమాణం', 'kn': 'ಅಂಗೀಕರಿಸಿದ ಪ್ರಮಾಣ', 'ml': 'സ്വീകരിച്ച അളവ്', 'or': 'ଗୃହୀତ ପରିମାଣ', 'pa': 'ਮਨਜ਼ੂਰ ਮਾਤਰਾ', 'as': 'গ্ৰহণ কৰা পৰিমাণ'},
    'open': {'hi': 'खुला', 'bn': 'খোলা', 'mr': 'खुले', 'gu': 'ખુલ્લું', 'ta': 'திறந்துள்ளது', 'te': 'ఓపెన్', 'kn': 'ತೆರೆದಿದೆ', 'ml': 'തുറന്നത്', 'or': 'ଖୋଲା', 'pa': 'ਖੁੱਲ੍ਹਾ', 'as': 'খোলা'},
    'partiallyFulfilled': {'hi': 'आंशिक रूप से पूर्ण', 'bn': 'আংশিক পূর্ণ', 'mr': 'अंशतः पूर्ण', 'gu': 'અંશતઃ પૂર્ણ', 'ta': 'பகுதியாக நிறைவேற்றப்பட்டது', 'te': 'పాక్షికంగా నెరవేరింది', 'kn': 'ಭಾಗಶಃ ಪೂರೈಸಲಾಗಿದೆ', 'ml': 'ഭാഗികമായി നിറവേറ്റി', 'or': 'ଆଂଶିକ ପୂରଣ ହୋଇଛି', 'pa': 'ਅੰਸ਼ਕ ਤੌਰ ਤੇ ਪੂਰਾ ਹੋਇਆ', 'as': 'আংশিকভাৱে পূৰণ কৰা হৈছে'},
    'fulfilled': {'hi': 'पूर्ण', 'bn': 'পূর্ণ', 'mr': 'पूर्ण', 'gu': 'પૂર્ણ', 'ta': 'நிறைவேற்றப்பட்டது', 'te': 'నెరవేరింది', 'kn': 'ಪೂರೈಸಲಾಗಿದೆ', 'ml': 'നിറവേറ്റി', 'or': 'ପୂରଣ ହୋଇଛି', 'pa': 'ਪੂਰਾ ਹੋਇਆ', 'as': 'পূৰণ কৰা হৈছে'},
    'submitted': {'hi': 'प्रस्तुत', 'bn': 'জমা দেওয়া হয়েছে', 'mr': 'सादर केले', 'gu': 'સબમિટ કર્યું', 'ta': 'சமர்ப்பிக்கப்பட்டது', 'te': 'సమర్పించబడింది', 'kn': 'ಸಲ್ಲಿಸಲಾಗಿದೆ', 'ml': 'സമർപ്പിച്ചു', 'or': 'ଦାଖଲ ହୋଇଛି', 'pa': 'ਜਮ੍ਹਾ ਕੀਤਾ ਗਿਆ', 'as': 'দাখিল কৰা হৈছে'},
    'rejected': {'hi': 'अस्वीकृत', 'bn': 'প্রত্যাখ্যাত', 'mr': 'नाकारले', 'gu': 'નકારાયેલ', 'ta': 'நிராகரிக்கப்பட்டது', 'te': 'తిరస్కరించబడింది', 'kn': 'ತಿರಸ್ಕರಿಸಲಾಗಿದೆ', 'ml': 'നിരസിച്ചു', 'or': 'ପ୍ରତ୍ୟାଖ୍ୟାନ କରାଯାଇଛି', 'pa': 'ਰੱਦ ਕੀਤਾ ਗਿਆ', 'as': 'প্ৰত্যাখ্যান কৰা হৈছে'},
    'withdrawn': {'hi': 'वापस लिया गया', 'bn': 'প্রত্যাহার করা হয়েছে', 'mr': 'मागे घेतले', 'gu': 'પાછું ખેંચ્યું', 'ta': 'திரும்பப் பெறப்பட்டது', 'te': 'ఉపసంహరించబడింది', 'kn': 'ಹಿಂಪಡೆಯಲಾಗಿದೆ', 'ml': 'പിൻവലിച്ചു', 'or': 'ପ୍ରତ୍ୟାହାର କରାଯାଇଛି', 'pa': 'ਵਾਪਸ ਲਿਆ ਗਿਆ', 'as': 'প্ৰত্যাহাৰ কৰা হৈছে'}
}

extended_translations = {
    'hi': {
        'validationRequired': 'यह फ़ील्ड आवश्यक है',
        'validationNumeric': 'कृपया एक वैध संख्या दर्ज करें',
        'edit': 'संपादित करें',
        'marketplace': 'बाज़ार',
        'search': 'खोजें',
        'nearbyProducts': 'आस-पास के उत्पाद',
        'all': 'सभी',
        'farmerId': 'किसान आईडी',
        'sort': 'क्रमबद्ध करें',
        'priceLowToHigh': 'कीमत: कम से ज्यादा',
        'priceHighToLow': 'कीमत: ज्यादा से कम',
        'nearest': 'निकटतम',
        'noProductsFound': 'कोई उत्पाद नहीं मिला',
        'clear': 'साफ़ करें',
        'viewDetails': 'विवरण देखें',
        'compare': 'तुलना करें',
        'comingSoon': 'जल्द आ रहा है',
        'buyNow': 'अभी खरीदें (जल्द आ रहा है)',
        'myCart': 'मेरा कार्ट',
        'addToCart': 'कार्ट में डालें',
        'addedToCart': 'कार्ट में डाला गया',
        'remove': 'हटाएं',
        'subtotal': 'उप-योग',
        'total': 'कुल',
        'grandTotal': 'कुल योग',
        'checkout': 'चेकआउट',
        'orderSummary': 'ऑर्डर सारांश',
        'placeOrder': 'ऑर्डर दें',
        'orderPlaced': 'ऑर्डर सफलतापूर्वक दिया गया',
        'orderId': 'ऑर्डर आईडी',
        'orderDetails': 'ऑर्डर विवरण',
        'placed': 'दिया गया',
        'preparing': 'तैयार हो रहा है',
        'readyForPickup': 'पिकअप के लिए तैयार',
        'completed': 'पूरा हुआ',
        'cancelled': 'रद्द किया गया',
        'cancelOrder': 'ऑर्डर रद्द करें',
        'confirmCancellation': 'क्या आप वाकई इस ऑर्डर को रद्द करना चाहते हैं?',
        'continueShopping': 'खरीदारी जारी रखें',
        'viewMyOrders': 'मेरे ऑर्डर देखें',
        'deliveryLocation': 'डिलीवरी स्थान',
        'paymentIntegrationComingSoon': 'भुगतान एकीकरण जल्द आ रहा है',
        'emptyCart': 'आपका कार्ट खाली है',
        'noOrders': 'कोई ऑर्डर नहीं मिला',
        'status': 'स्थिति',
        'date': 'तिथि',
        'items': 'आइटम',
        'farmerOrders': 'किसान ऑर्डर',
        'updateStatus': 'स्थिति अपडेट करें',
        'myRequirements': 'मेरी आवश्यकताएँ',
        'createRequirement': 'आवश्यकता बनाएँ',
        'product': 'उत्पाद',
        'requiredQuantity': 'आवश्यक मात्रा',
        'targetPrice': 'लक्षित मूल्य',
        'requiredBy': 'आवश्यकता द्वारा',
        'offers': 'प्रस्ताव',
        'viewOffers': 'प्रस्ताव देखें',
        'submitOffer': 'प्रस्ताव सबमिट करें',
        'availableQuantity': 'उपलब्ध मात्रा',
        'offeredPrice': 'प्रस्तावित मूल्य',
        'readyDate': 'तैयार होने की तिथि',
        'farmerNote': 'किसान का नोट',
        'acceptOffer': 'प्रस्ताव स्वीकार करें',
        'rejectOffer': 'प्रस्ताव अस्वीकार करें',
        'withdrawOffer': 'प्रस्ताव वापस लें',
        'remainingQuantity': 'शेष मात्रा',
        'expired': 'समाप्त',
        'shortlisted': 'शॉर्टलिस्ट किया गया',
        'bestQuality': 'सर्वोत्तम गुणवत्ता',
        'earliestReadyDate': 'सबसे जल्दी तैयार होने की तिथि',
        'noRequirements': 'कोई आवश्यकता नहीं मिली',
        'noOffers': 'कोई प्रस्ताव नहीं मिला',
        'target': 'लक्ष्य',
        'publish': 'प्रकाशित करें',
        'compareOffers': 'प्रस्तावों की तुलना करें',
        'buyer': 'खरीदार'
    },
    'bn': {
        'validationRequired': 'এই ক্ষেত্রটি আবশ্যক',
        'validationNumeric': 'একটি বৈধ সংখ্যা লিখুন',
        'edit': 'সম্পাদনা করুন',
        'marketplace': 'মার্কেটপ্লেস',
        'search': 'অনুসন্ধান করুন',
        'nearbyProducts': 'কাছাকাছি পণ্য',
        'all': 'সব',
        'farmerId': 'কৃষক আইডি',
        'sort': 'বাছাই করুন',
        'priceLowToHigh': 'দাম: কম থেকে বেশি',
        'priceHighToLow': 'দাম: বেশি থেকে কম',
        'nearest': 'নিকটতম',
        'noProductsFound': 'কোনো পণ্য পাওয়া যায়নি',
        'clear': 'পরিষ্কার করুন',
        'viewDetails': 'বিবরণ দেখুন',
        'compare': 'তুলনা করুন',
        'comingSoon': 'শীঘ্রই আসছে',
        'buyNow': 'এখন কিনুন (শীঘ্রই আসছে)',
        'myCart': 'আমার কার্ট',
        'addToCart': 'কার্টে যোগ করুন',
        'addedToCart': 'কার্টে যোগ করা হয়েছে',
        'remove': 'সরান',
        'subtotal': 'সাবটোটাল',
        'total': 'মোট',
        'grandTotal': 'সর্বমোট',
        'checkout': 'চেকআউট',
        'orderSummary': 'অর্ডার সারাংশ',
        'placeOrder': 'অর্ডার দিন',
        'orderPlaced': 'অর্ডার সফলভাবে দেওয়া হয়েছে',
        'orderId': 'অর্ডার আইডি',
        'orderDetails': 'অর্ডারের বিবরণ',
        'placed': 'দেওয়া হয়েছে',
        'preparing': 'প্রস্তুত হচ্ছে',
        'readyForPickup': 'পিকআপের জন্য প্রস্তুত',
        'completed': 'সম্পন্ন',
        'cancelled': 'বাতিল করা হয়েছে',
        'cancelOrder': 'অর্ডার বাতিল করুন',
        'confirmCancellation': 'আপনি কি নিশ্চিত যে আপনি এই অর্ডারটি বাতিল করতে চান?',
        'continueShopping': 'কেনাকাটা চালিয়ে যান',
        'viewMyOrders': 'আমার অর্ডার দেখুন',
        'deliveryLocation': 'ডেলিভারি অবস্থান',
        'paymentIntegrationComingSoon': 'পেমেন্ট ইন্টিগ্রেশন শীঘ্রই আসছে',
        'emptyCart': 'আপনার কার্ট খালি',
        'noOrders': 'কোনো অর্ডার পাওয়া যায়নি',
        'status': 'স্ট্যাটাস',
        'date': 'তারিখ',
        'items': 'আইটেম',
        'farmerOrders': 'কৃষকের অর্ডার',
        'updateStatus': 'স্ট্যাটাস আপডেট করুন',
        'myRequirements': 'আমার প্রয়োজনীয়তা',
        'createRequirement': 'প্রয়োজনীয়তা তৈরি করুন',
        'product': 'পণ্য',
        'requiredQuantity': 'প্রয়োজনীয় পরিমাণ',
        'targetPrice': 'লক্ষ্য মূল্য',
        'requiredBy': 'প্রয়োজন',
        'offers': 'অফার',
        'viewOffers': 'অফার দেখুন',
        'submitOffer': 'অফার জমা দিন',
        'availableQuantity': 'উপলব্ধ পরিমাণ',
        'offeredPrice': 'অফার মূল্য',
        'readyDate': 'প্রস্তুত তারিখ',
        'farmerNote': 'কৃষকের নোট',
        'acceptOffer': 'অফার গ্রহণ করুন',
        'rejectOffer': 'অফার প্রত্যাখ্যান করুন',
        'withdrawOffer': 'অফার প্রত্যাহার করুন',
        'remainingQuantity': 'অবশিষ্ট পরিমাণ',
        'expired': 'মেয়াদোত্তীর্ণ',
        'shortlisted': 'বাছাই করা হয়েছে',
        'bestQuality': 'সেরা গুণমান',
        'earliestReadyDate': 'প্রাথমিক প্রস্তুতির তারিখ',
        'noRequirements': 'কোনো প্রয়োজনীয়তা পাওয়া যায়নি',
        'noOffers': 'কোনো অফার পাওয়া যায়নি',
        'target': 'লক্ষ্য',
        'publish': 'প্রকাশ করুন',
        'compareOffers': 'অফারের তুলনা করুন',
        'buyer': 'ক্রেতা'
    },
    'mr': {
        'validationRequired': 'हे क्षेत्र आवश्यक आहे',
        'validationNumeric': 'कृपया वैध संख्या प्रविष्ट करा',
        'edit': 'संपादित करा',
        'marketplace': 'बाजारपेठ',
        'search': 'शोधा',
        'nearbyProducts': 'जवळील उत्पादने',
        'all': 'सर्व',
        'farmerId': 'शेतकरी आयडी',
        'sort': 'क्रमवारी लावा',
        'priceLowToHigh': 'किंमत: कमी ते जास्त',
        'priceHighToLow': 'किंमत: जास्त ते कमी',
        'nearest': 'जवळचे',
        'noProductsFound': 'कोणतीही उत्पादने आढळली नाहीत',
        'clear': 'साफ करा',
        'viewDetails': 'तपशील पहा',
        'compare': 'तुलना करा',
        'comingSoon': 'लवकरच येत आहे',
        'buyNow': 'आता खरेदी करा (लवकरच येत आहे)',
        'myCart': 'माझे कार्ट',
        'addToCart': 'कार्टमध्ये जोडा',
        'addedToCart': 'कार्टमध्ये जोडले',
        'remove': 'काढून टाका',
        'subtotal': 'उप-एकूण',
        'total': 'एकूण',
        'grandTotal': 'एकूण रक्कम',
        'checkout': 'चेकआउट',
        'orderSummary': 'ऑर्डर सारांश',
        'placeOrder': 'ऑर्डर द्या',
        'orderPlaced': 'ऑर्डर यशस्वीरित्या दिली',
        'orderId': 'ऑर्डर आयडी',
        'orderDetails': 'ऑर्डर तपशील',
        'placed': 'दिली',
        'preparing': 'तयार करत आहे',
        'readyForPickup': 'पिकअपसाठी तयार',
        'completed': 'पूर्ण',
        'cancelled': 'रद्द केले',
        'cancelOrder': 'ऑर्डर रद्द करा',
        'confirmCancellation': 'तुम्हाला नक्की ही ऑर्डर रद्द करायची आहे का?',
        'continueShopping': 'खरेदी सुरू ठेवा',
        'viewMyOrders': 'माझ्या ऑर्डर पहा',
        'deliveryLocation': 'वितरण ठिकाण',
        'paymentIntegrationComingSoon': 'पेमेंट इंटिग्रेशन लवकरच येत आहे',
        'emptyCart': 'तुमचे कार्ट रिक्त आहे',
        'noOrders': 'कोणत्याही ऑर्डर आढळल्या नाहीत',
        'status': 'स्थिती',
        'date': 'तारीख',
        'items': 'आयटम',
        'farmerOrders': 'शेतकरी ऑर्डर',
        'updateStatus': 'स्थिती अपडेट करा',
        'myRequirements': 'माझ्या आवश्यकता',
        'createRequirement': 'आवश्यकता तयार करा',
        'product': 'उत्पादन',
        'requiredQuantity': 'आवश्यक प्रमाण',
        'targetPrice': 'लक्ष्य किंमत',
        'requiredBy': 'आवश्यक',
        'offers': 'ऑफर',
        'viewOffers': 'ऑफर पहा',
        'submitOffer': 'ऑफर सबमिट करा',
        'availableQuantity': 'उपलब्ध प्रमाण',
        'offeredPrice': 'ऑफर किंमत',
        'readyDate': 'तयार तारीख',
        'farmerNote': 'शेतकरी नोंद',
        'acceptOffer': 'ऑफर स्वीकारा',
        'rejectOffer': 'ऑफर नाकारा',
        'withdrawOffer': 'ऑफर मागे घ्या',
        'remainingQuantity': 'उर्वरित प्रमाण',
        'expired': 'कालबाह्य',
        'shortlisted': 'शॉर्टलिस्ट केले',
        'bestQuality': 'उत्तम गुणवत्ता',
        'earliestReadyDate': 'लवकर तयार तारीख',
        'noRequirements': 'कोणत्याही आवश्यकता आढळल्या नाहीत',
        'noOffers': 'कोणत्याही ऑफर आढळल्या नाहीत',
        'target': 'लक्ष्य',
        'publish': 'प्रकाशित करा',
        'compareOffers': 'ऑफरची तुलना करा',
        'buyer': 'खरेदीदार'
    },
    'gu': {
        'validationRequired': 'આ ફીલ્ડ આવશ્યક છે',
        'validationNumeric': 'કૃપા કરીને માન્ય નંબર દાખલ કરો',
        'edit': 'સંપાદિત કરો',
        'marketplace': 'બજાર',
        'search': 'શોધો',
        'nearbyProducts': 'નજીકના ઉત્પાદનો',
        'all': 'બધા',
        'farmerId': 'ખેડૂત ID',
        'sort': 'સૉર્ટ કરો',
        'priceLowToHigh': 'કિંમત: ઓછી થી વધુ',
        'priceHighToLow': 'કિંમત: વધુ થી ઓછી',
        'nearest': 'નજીકનું',
        'noProductsFound': 'કોઈ ઉત્પાદનો મળ્યા નથી',
        'clear': 'સાફ કરો',
        'viewDetails': 'વિગતો જુઓ',
        'compare': 'સરખામણી કરો',
        'comingSoon': 'જલ્દી આવી રહ્યું છે',
        'buyNow': 'હમણાં ખરીદો (જલ્દી આવી રહ્યું છે)',
        'myCart': 'મારું કાર્ટ',
        'addToCart': 'કાર્ટમાં ઉમેરો',
        'addedToCart': 'કાર્ટમાં ઉમેર્યું',
        'remove': 'દૂર કરો',
        'subtotal': 'પેટા સરવાળો',
        'total': 'કુલ',
        'grandTotal': 'ગ્રાન્ડ ટોટલ',
        'checkout': 'ચેકઆઉટ',
        'orderSummary': 'ઓર્ડર સારાંશ',
        'placeOrder': 'ઓર્ડર આપો',
        'orderPlaced': 'ઓર્ડર સફળતાપૂર્વક અપાયો',
        'orderId': 'ઓર્ડર ID',
        'orderDetails': 'ઓર્ડર વિગતો',
        'placed': 'મૂકેલ',
        'preparing': 'તૈયાર થઈ રહ્યું છે',
        'readyForPickup': 'પિકઅપ માટે તૈયાર',
        'completed': 'પૂર્ણ',
        'cancelled': 'રદ કરેલ',
        'cancelOrder': 'ઓર્ડર રદ કરો',
        'confirmCancellation': 'શું તમે ખરેખર આ ઓર્ડર રદ કરવા માંગો છો?',
        'continueShopping': 'ખરીદી ચાલુ રાખો',
        'viewMyOrders': 'મારા ઓર્ડર જુઓ',
        'deliveryLocation': 'ડિલિવરી સ્થાન',
        'paymentIntegrationComingSoon': 'ચુકવણી એકીકરણ જલ્દી આવી રહ્યું છે',
        'emptyCart': 'તમારું કાર્ટ ખાલી છે',
        'noOrders': 'કોઈ ઓર્ડર મળ્યા નથી',
        'status': 'સ્થિતિ',
        'date': 'તારીખ',
        'items': 'આઇટમ્સ',
        'farmerOrders': 'ખેડૂત ઓર્ડર',
        'updateStatus': 'સ્થિતિ અપડેટ કરો',
        'myRequirements': 'મારી જરૂરિયાતો',
        'createRequirement': 'જરૂરિયાત બનાવો',
        'product': 'ઉત્પાદન',
        'requiredQuantity': 'જરૂરી જથ્થો',
        'targetPrice': 'લક્ષ્યાંક કિંમત',
        'requiredBy': 'દ્વારા જરૂરી',
        'offers': 'ઑફર્સ',
        'viewOffers': 'ઑફર્સ જુઓ',
        'submitOffer': 'ઑફર સબમિટ કરો',
        'availableQuantity': 'ઉપલબ્ધ જથ્થો',
        'offeredPrice': 'ઑફર કિંમત',
        'readyDate': 'તૈયાર તારીખ',
        'farmerNote': 'ખેડૂત નોંધ',
        'acceptOffer': 'ઑફર સ્વીકારો',
        'rejectOffer': 'ઑફર નકારો',
        'withdrawOffer': 'ઑફર પાછી ખેંચો',
        'remainingQuantity': 'બાકી જથ્થો',
        'expired': 'સમાપ્ત',
        'shortlisted': 'શોર્ટલિસ્ટ કરેલ',
        'bestQuality': 'શ્રેષ્ઠ ગુણવત્તા',
        'earliestReadyDate': 'પ્રારંભિક તૈયાર તારીખ',
        'noRequirements': 'કોઈ જરૂરિયાતો મળી નથી',
        'noOffers': 'કોઈ ઑફર્સ મળી નથી',
        'target': 'લક્ષ્ય',
        'publish': 'પ્રકાશિત કરો',
        'compareOffers': 'ઑફર્સની સરખામણી કરો',
        'buyer': 'ખરીદનાર'
    },
    'ta': {
        'validationRequired': 'இந்த புலம் அவசியம்',
        'validationNumeric': 'சரியான எண்ணை உள்ளிடவும்',
        'edit': 'திருத்து',
        'marketplace': 'சந்தை',
        'search': 'தேடு',
        'nearbyProducts': 'அருகிலுள்ள தயாரிப்புகள்',
        'all': 'அனைத்தும்',
        'farmerId': 'விவசாயி ஐடி',
        'sort': 'வரிசைப்படுத்து',
        'priceLowToHigh': 'விலை: குறைவு முதல் அதிகம்',
        'priceHighToLow': 'விலை: அதிகம் முதல் குறைவு',
        'nearest': 'அருகில்',
        'noProductsFound': 'எந்த தயாரிப்புகளும் காணப்படவில்லை',
        'clear': 'அழி',
        'viewDetails': 'விவரங்களை காண்',
        'compare': 'ஒப்பிடு',
        'comingSoon': 'விரைவில்',
        'buyNow': 'இப்போது வாங்கவும் (விரைவில்)',
        'myCart': 'எனது கார்ட்',
        'addToCart': 'கார்ட்டில் சேர்',
        'addedToCart': 'கார்ட்டில் சேர்க்கப்பட்டது',
        'remove': 'அகற்று',
        'subtotal': 'உப மொத்தம்',
        'total': 'மொத்தம்',
        'grandTotal': 'முழு மொத்தம்',
        'checkout': 'செக்அவுட்',
        'orderSummary': 'ஆர்டர் சுருக்கம்',
        'placeOrder': 'ஆர்டர் செய்',
        'orderPlaced': 'ஆர்டர் வெற்றிகரமாக செய்யப்பட்டது',
        'orderId': 'ஆர்டர் ஐடி',
        'orderDetails': 'ஆர்டர் விவரங்கள்',
        'placed': 'செய்யப்பட்டது',
        'preparing': 'தயாராகிறது',
        'readyForPickup': 'பிக்-அப்பிற்கு தயார்',
        'completed': 'முடிந்தது',
        'cancelled': 'ரத்து செய்யப்பட்டது',
        'cancelOrder': 'ஆர்டரை ரத்து செய்',
        'confirmCancellation': 'இந்த ஆர்டரை நீங்கள் நிச்சயமாக ரத்து செய்ய விரும்புகிறீர்களா?',
        'continueShopping': 'தொடர்ந்து ஷாப்பிங் செய்',
        'viewMyOrders': 'எனது ஆர்டர்களைக் காண்',
        'deliveryLocation': 'டெலிவரி இடம்',
        'paymentIntegrationComingSoon': 'கட்டண ஒருங்கிணைப்பு விரைவில்',
        'emptyCart': 'உங்கள் கார்ட் காலியாக உள்ளது',
        'noOrders': 'ஆர்டர்கள் எதுவும் இல்லை',
        'status': 'நிலை',
        'date': 'தேதி',
        'items': 'பொருட்கள்',
        'farmerOrders': 'விவசாயி ஆர்டர்கள்',
        'updateStatus': 'நிலையைப் புதுப்பி',
        'myRequirements': 'எனது தேவைகள்',
        'createRequirement': 'தேவையை உருவாக்கு',
        'product': 'தயாரிப்பு',
        'requiredQuantity': 'தேவையான அளவு',
        'targetPrice': 'இலக்கு விலை',
        'requiredBy': 'தேவைப்படுபவர்',
        'offers': 'சலுகைகள்',
        'viewOffers': 'சலுகைகளை காண்',
        'submitOffer': 'சலுகையை சமர்ப்பி',
        'availableQuantity': 'கிடைக்கும் அளவு',
        'offeredPrice': 'சலுகை விலை',
        'readyDate': 'தயார் தேதி',
        'farmerNote': 'விவசாயி குறிப்பு',
        'acceptOffer': 'சலுகையை ஏற்றுக்கொள்',
        'rejectOffer': 'சலுகையை நிராகரி',
        'withdrawOffer': 'சலுகையை திரும்பப் பெறு',
        'remainingQuantity': 'மீதமுள்ள அளவு',
        'expired': 'காலாவதியானது',
        'shortlisted': 'தேர்ந்தெடுக்கப்பட்டது',
        'bestQuality': 'சிறந்த தரம்',
        'earliestReadyDate': 'ஆரம்ப தயார் தேதி',
        'noRequirements': 'தேவைகள் காணப்படவில்லை',
        'noOffers': 'சலுகைகள் காணப்படவில்லை',
        'target': 'இலக்கு',
        'publish': 'வெளியிடு',
        'compareOffers': 'சலுகைகளை ஒப்பிடு',
        'buyer': 'வாங்குபவர்'
    },
    'te': {
        'validationRequired': 'ఈ ఫీల్డ్ అవసరం',
        'validationNumeric': 'దయచేసి చెల్లుబాటు అయ్యే సంఖ్యను నమోదు చేయండి',
        'edit': 'సవరించు',
        'marketplace': 'మార్కెట్',
        'search': 'శోధించు',
        'nearbyProducts': 'సమీప ఉత్పత్తులు',
        'all': 'అన్ని',
        'farmerId': 'రైతు ID',
        'sort': 'క్రమబద్ధీకరించు',
        'priceLowToHigh': 'ధర: తక్కువ నుండి ఎక్కువ',
        'priceHighToLow': 'ధర: ఎక్కువ నుండి తక్కువ',
        'nearest': 'సమీప',
        'noProductsFound': 'ఎలాంటి ఉత్పత్తులు కనుగొనబడలేదు',
        'clear': 'క్లియర్',
        'viewDetails': 'వివరాలు చూడండి',
        'compare': 'సరిపోల్చండి',
        'comingSoon': 'త్వరలో',
        'buyNow': 'ఇప్పుడు కొనండి (త్వరలో)',
        'myCart': 'నా కార్ట్',
        'addToCart': 'కార్ట్ కు జోడించు',
        'addedToCart': 'కార్ట్ కు జోడించబడింది',
        'remove': 'తొలగించు',
        'subtotal': 'ఉప-మొత్తం',
        'total': 'మొత్తం',
        'grandTotal': 'గ్రాండ్ టోటల్',
        'checkout': 'చెక్అవుట్',
        'orderSummary': 'ఆర్డర్ సారాంశం',
        'placeOrder': 'ఆర్డర్ చేయండి',
        'orderPlaced': 'ఆర్డర్ విజయవంతంగా చేయబడింది',
        'orderId': 'ఆర్డర్ ID',
        'orderDetails': 'ఆర్డర్ వివరాలు',
        'placed': 'చేయబడింది',
        'preparing': 'సిద్ధమవుతోంది',
        'readyForPickup': 'పికప్ కు సిద్ధంగా ఉంది',
        'completed': 'పూర్తయింది',
        'cancelled': 'రద్దు చేయబడింది',
        'cancelOrder': 'ఆర్డర్ రద్దు చేయండి',
        'confirmCancellation': 'మీరు ఖచ్చితంగా ఈ ఆర్డర్ ను రద్దు చేయాలనుకుంటున్నారా?',
        'continueShopping': 'షాపింగ్ కొనసాగించండి',
        'viewMyOrders': 'నా ఆర్డర్లను చూడండి',
        'deliveryLocation': 'డెలివరీ స్థానం',
        'paymentIntegrationComingSoon': 'చెల్లింపు అనుసంధానం త్వరలో',
        'emptyCart': 'మీ కార్ట్ ఖాళీగా ఉంది',
        'noOrders': 'ఎలాంటి ఆర్డర్లు కనుగొనబడలేదు',
        'status': 'స్థితి',
        'date': 'తేదీ',
        'items': 'అంశాలు',
        'farmerOrders': 'రైతు ఆర్డర్లు',
        'updateStatus': 'స్థితిని నవీకరించండి',
        'myRequirements': 'నా అవసరాలు',
        'createRequirement': 'అవసరాన్ని సృష్టించండి',
        'product': 'ఉత్పత్తి',
        'requiredQuantity': 'అవసరమైన పరిమాణం',
        'targetPrice': 'లక్ష్య ధర',
        'requiredBy': 'అవసరం',
        'offers': 'ఆఫర్లు',
        'viewOffers': 'ఆఫర్లను చూడండి',
        'submitOffer': 'ఆఫర్ను సమర్పించండి',
        'availableQuantity': 'అందుబాటులో ఉన్న పరిమాణం',
        'offeredPrice': 'ఆఫర్ ధర',
        'readyDate': 'సిద్ధంగా ఉన్న తేదీ',
        'farmerNote': 'రైతు గమనిక',
        'acceptOffer': 'ఆఫర్ను అంగీకరించండి',
        'rejectOffer': 'ఆఫర్ను తిరస్కరించండి',
        'withdrawOffer': 'ఆఫర్ను ఉపసంహరించుకోండి',
        'remainingQuantity': 'మిగిలిన పరిమాణం',
        'expired': 'గడువు ముగిసింది',
        'shortlisted': 'షార్ట్‌లిస్ట్ చేయబడింది',
        'bestQuality': 'ఉత్తమ నాణ్యత',
        'earliestReadyDate': 'ముందస్తు సిద్ధంగా ఉన్న తేదీ',
        'noRequirements': 'ఎలాంటి అవసరాలు కనుగొనబడలేదు',
        'noOffers': 'ఎలాంటి ఆఫర్లు కనుగొనబడలేదు',
        'target': 'లక్ష్యం',
        'publish': 'ప్రచురించు',
        'compareOffers': 'ఆఫర్లను సరిపోల్చండి',
        'buyer': 'కొనుగోలుదారు'
    },
    'kn': {
        'validationRequired': 'ಈ ಕ್ಷೇತ್ರವು ಅಗತ್ಯವಿದೆ',
        'validationNumeric': 'ದಯವಿಟ್ಟು ಮಾನ್ಯವಾದ ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ',
        'edit': 'ತಿದ್ದಿ',
        'marketplace': 'ಮಾರುಕಟ್ಟೆ',
        'search': 'ಹುಡುಕು',
        'nearbyProducts': 'ಹತ್ತಿರದ ಉತ್ಪನ್ನಗಳು',
        'all': 'ಎಲ್ಲಾ',
        'farmerId': 'ರೈತ ID',
        'sort': 'ವಿಂಗಡಿಸು',
        'priceLowToHigh': 'ಬೆಲೆ: ಕಡಿಮೆಯಿಂದ ಹೆಚ್ಚು',
        'priceHighToLow': 'ಬೆಲೆ: ಹೆಚ್ಚುವರಿಯಿಂದ ಕಡಿಮೆ',
        'nearest': 'ಹತ್ತಿರದ',
        'noProductsFound': 'ಯಾವುದೇ ಉತ್ಪನ್ನಗಳು ಕಂಡುಬಂದಿಲ್ಲ',
        'clear': 'ತೆರವುಗೊಳಿಸಿ',
        'viewDetails': 'ವಿವರಗಳನ್ನು ವೀಕ್ಷಿಸಿ',
        'compare': 'ಹೋಲಿಸಿ',
        'comingSoon': 'ಶೀಘ್ರದಲ್ಲೇ ಬರಲಿದೆ',
        'buyNow': 'ಈಗ ಖರೀದಿಸಿ (ಶೀಘ್ರದಲ್ಲೇ ಬರಲಿದೆ)',
        'myCart': 'ನನ್ನ ಕಾರ್ಟ್',
        'addToCart': 'ಕಾರ್ಟ್‌ಗೆ ಸೇರಿಸಿ',
        'addedToCart': 'ಕಾರ್ಟ್‌ಗೆ ಸೇರಿಸಲಾಗಿದೆ',
        'remove': 'ತೆಗೆದುಹಾಕಿ',
        'subtotal': 'ಉಪಮೊತ್ತ',
        'total': 'ಒಟ್ಟು',
        'grandTotal': 'ಮಹಾ ಒಟ್ಟು',
        'checkout': 'ಚೆಕ್‌ಔಟ್',
        'orderSummary': 'ಆರ್ಡರ್ ಸಾರಾಂಶ',
        'placeOrder': 'ಆರ್ಡರ್ ಮಾಡಿ',
        'orderPlaced': 'ಆರ್ಡರ್ ಯಶಸ್ವಿಯಾಗಿ ಮಾಡಲಾಗಿದೆ',
        'orderId': 'ಆರ್ಡರ್ ID',
        'orderDetails': 'ಆರ್ಡರ್ ವಿವರಗಳು',
        'placed': 'ಮಾಡಲಾಗಿದೆ',
        'preparing': 'ಸಿದ್ಧಪಡಿಸಲಾಗುತ್ತಿದೆ',
        'readyForPickup': 'ಪಿಕಪ್‌ಗೆ ಸಿದ್ಧವಾಗಿದೆ',
        'completed': 'ಪೂರ್ಣಗೊಂಡಿದೆ',
        'cancelled': 'ರದ್ದುಗೊಳಿಸಲಾಗಿದೆ',
        'cancelOrder': 'ಆರ್ಡರ್ ರದ್ದುಗೊಳಿಸಿ',
        'confirmCancellation': 'ನೀವು ಖಂಡಿತವಾಗಿ ಈ ಆರ್ಡರ್ ಅನ್ನು ರದ್ದುಗೊಳಿಸಲು ಬಯಸುವಿರಾ?',
        'continueShopping': 'ಶಾಪಿಂಗ್ ಮುಂದುವರಿಸಿ',
        'viewMyOrders': 'ನನ್ನ ಆರ್ಡರ್‌ಗಳನ್ನು ವೀಕ್ಷಿಸಿ',
        'deliveryLocation': 'ವಿತರಣಾ ಸ್ಥಳ',
        'paymentIntegrationComingSoon': 'ಪಾವತಿ ಏಕೀಕರಣ ಶೀಘ್ರದಲ್ಲೇ ಬರಲಿದೆ',
        'emptyCart': 'ನಿಮ್ಮ ಕಾರ್ಟ್ ಖಾಲಿಯಾಗಿದೆ',
        'noOrders': 'ಯಾವುದೇ ಆರ್ಡರ್‌ಗಳು ಕಂಡುಬಂದಿಲ್ಲ',
        'status': 'ಸ್ಥಿತಿ',
        'date': 'ದಿನಾಂಕ',
        'items': 'ಐಟಂಗಳು',
        'farmerOrders': 'ರೈತರ ಆರ್ಡರ್‌ಗಳು',
        'updateStatus': 'ಸ್ಥಿತಿಯನ್ನು ನವೀಕರಿಸಿ',
        'myRequirements': 'ನನ್ನ ಅಗತ್ಯತೆಗಳು',
        'createRequirement': 'ಅಗತ್ಯವನ್ನು ರಚಿಸಿ',
        'product': 'ಉತ್ಪನ್ನ',
        'requiredQuantity': 'ಅಗತ್ಯ ಪ್ರಮಾಣ',
        'targetPrice': 'ಗುರಿ ಬೆಲೆ',
        'requiredBy': 'ಅಗತ್ಯವಿದೆ',
        'offers': 'ಕೊಡುಗೆಗಳು',
        'viewOffers': 'ಕೊಡುಗೆಗಳನ್ನು ವೀಕ್ಷಿಸಿ',
        'submitOffer': 'ಕೊಡುಗೆಯನ್ನು ಸಲ್ಲಿಸಿ',
        'availableQuantity': 'ಲಭ್ಯವಿರುವ ಪ್ರಮಾಣ',
        'offeredPrice': 'ಕೊಡುಗೆ ಬೆಲೆ',
        'readyDate': 'ಸಿದ್ಧ ದಿನಾಂಕ',
        'farmerNote': 'ರೈತರ ಟಿಪ್ಪಣಿ',
        'acceptOffer': 'ಕೊಡುಗೆಯನ್ನು ಸ್ವೀಕರಿಸಿ',
        'rejectOffer': 'ಕೊಡುಗೆಯನ್ನು ತಿರಸ್ಕರಿಸಿ',
        'withdrawOffer': 'ಕೊಡುಗೆಯನ್ನು ಹಿಂಪಡೆಯಿರಿ',
        'remainingQuantity': 'ಉಳಿದ ಪ್ರಮಾಣ',
        'expired': 'ಅವಧಿ ಮುಗಿದಿದೆ',
        'shortlisted': 'ಶಾರ್ಟ್‌ಲಿಸ್ಟ್ ಮಾಡಲಾಗಿದೆ',
        'bestQuality': 'ಅತ್ಯುತ್ತಮ ಗುಣಮಟ್ಟ',
        'earliestReadyDate': 'ಆರಂಭಿಕ ಸಿದ್ಧ ದಿನಾಂಕ',
        'noRequirements': 'ಯಾವುದೇ ಅಗತ್ಯತೆಗಳು ಕಂಡುಬಂದಿಲ್ಲ',
        'noOffers': 'ಯಾವುದೇ ಕೊಡುಗೆಗಳು ಕಂಡುಬಂದಿಲ್ಲ',
        'target': 'ಗುರಿ',
        'publish': 'ಪ್ರಕಟಿಸು',
        'compareOffers': 'ಕೊಡುಗೆಗಳನ್ನು ಹೋಲಿಸಿ',
        'buyer': 'ಖರೀದಿದಾರ'
    },
    'ml': {
        'validationRequired': 'ഈ ഫീൽഡ് നിർബന്ധമാണ്',
        'validationNumeric': 'സാധുവായ നമ്പർ നൽകുക',
        'edit': 'തിരുത്തുക',
        'marketplace': 'മാർക്കറ്റ് പ്ലേസ്',
        'search': 'തിരയുക',
        'nearbyProducts': 'സമീപമുള്ള ഉൽപ്പന്നങ്ങൾ',
        'all': 'എല്ലാം',
        'farmerId': 'കർഷക ഐഡി',
        'sort': 'ക്രമീകരിക്കുക',
        'priceLowToHigh': 'വില: കുറവിൽ നിന്ന് കൂടുതൽ',
        'priceHighToLow': 'വില: കൂടുതലിൽ നിന്ന് കുറവ്',
        'nearest': 'ഏറ്റവും അടുത്തുള്ള',
        'noProductsFound': 'ഉൽപ്പന്നങ്ങളൊന്നും കണ്ടെത്തിയില്ല',
        'clear': 'വ്യക്തമാക്കുക',
        'viewDetails': 'വിശദാംശങ്ങൾ കാണുക',
        'compare': 'താരതമ്യം ചെയ്യുക',
        'comingSoon': 'ഉടൻ വരുന്നു',
        'buyNow': 'ഇപ്പോൾ വാങ്ങുക (ഉടൻ വരുന്നു)',
        'myCart': 'എന്റെ കാർട്ട്',
        'addToCart': 'കാർട്ടിലേക്ക് ചേർക്കുക',
        'addedToCart': 'കാർട്ടിലേക്ക് ചേർത്തു',
        'remove': 'നീക്കം ചെയ്യുക',
        'subtotal': 'ഉപമൊത്തം',
        'total': 'മൊത്തം',
        'grandTotal': 'ഗ്രാൻഡ് ടോട്ടൽ',
        'checkout': 'ചെക്ക്ഔട്ട്',
        'orderSummary': 'ഓർഡർ സംഗ്രഹം',
        'placeOrder': 'ഓർഡർ ചെയ്യുക',
        'orderPlaced': 'ഓർഡർ വിജയകരമായി നൽകി',
        'orderId': 'ഓർഡർ ഐഡി',
        'orderDetails': 'ഓർഡർ വിശദാംശങ്ങൾ',
        'placed': 'നൽകി',
        'preparing': 'തയ്യാറാക്കുന്നു',
        'readyForPickup': 'പിക്കപ്പിന് തയ്യാറാണ്',
        'completed': 'പൂർത്തിയായി',
        'cancelled': 'റദ്ദാക്കി',
        'cancelOrder': 'ഓർഡർ റദ്ദാക്കുക',
        'confirmCancellation': 'ഈ ഓർഡർ റദ്ദാക്കണമെന്ന് നിങ്ങൾക്ക് ഉറപ്പാണോ?',
        'continueShopping': 'ഷോപ്പിംഗ് തുടരുക',
        'viewMyOrders': 'എന്റെ ഓർഡറുകൾ കാണുക',
        'deliveryLocation': 'ഡെലിവറി സ്ഥലം',
        'paymentIntegrationComingSoon': 'പേയ്‌മെന്റ് ഇന്റഗ്രേഷൻ ഉടൻ വരുന്നു',
        'emptyCart': 'നിങ്ങളുടെ കാർട്ട് ശൂന്യമാണ്',
        'noOrders': 'ഓർഡറുകളൊന്നും കണ്ടെത്തിയില്ല',
        'status': 'സ്റ്റാറ്റസ്',
        'date': 'തീയതി',
        'items': 'ഇനങ്ങൾ',
        'farmerOrders': 'കർഷക ഓർഡറുകൾ',
        'updateStatus': 'സ്റ്റാറ്റസ് അപ്‌ഡേറ്റ് ചെയ്യുക',
        'myRequirements': 'എന്റെ ആവശ്യകതകൾ',
        'createRequirement': 'ആവശ്യകത സൃഷ്ടിക്കുക',
        'product': 'ഉൽപ്പന്നം',
        'requiredQuantity': 'ആവശ്യമായ അളവ്',
        'targetPrice': 'ലക്ഷ്യ വില',
        'requiredBy': 'ആവശ്യമുള്ളത്',
        'offers': 'ഓഫറുകൾ',
        'viewOffers': 'ഓഫറുകൾ കാണുക',
        'submitOffer': 'ഓഫർ സമർപ്പിക്കുക',
        'availableQuantity': 'ലഭ്യമായ അളവ്',
        'offeredPrice': 'ഓഫർ വില',
        'readyDate': 'തയ്യാറായ തീയതി',
        'farmerNote': 'കർഷകന്റെ കുറിപ്പ്',
        'acceptOffer': 'ഓഫർ സ്വീകരിക്കുക',
        'rejectOffer': 'ഓഫർ നിരസിക്കുക',
        'withdrawOffer': 'ഓഫർ പിൻവലിക്കുക',
        'remainingQuantity': 'ബാക്കിയുള്ള അളവ്',
        'expired': 'കാലാവധി കഴിഞ്ഞു',
        'shortlisted': 'ഷോർട്ട്‌ലിസ്റ്റ് ചെയ്തു',
        'bestQuality': 'മികച്ച നിലവാരം',
        'earliestReadyDate': 'ഏറ്റവും നേരത്തെയുള്ള തയ്യാറായ തീയതി',
        'noRequirements': 'ആവശ്യകതകളൊന്നും കണ്ടെത്തിയില്ല',
        'noOffers': 'ഓഫറുകളൊന്നും കണ്ടെത്തിയില്ല',
        'target': 'ലക്ഷ്യം',
        'publish': 'പ്രസിദ്ധീകരിക്കുക',
        'compareOffers': 'ഓഫറുകൾ താരതമ്യം ചെയ്യുക',
        'buyer': 'വാങ്ങുന്നയാൾ'
    },
    'or': {
        'validationRequired': 'ଏହି କ୍ଷେତ୍ରଟି ଆବଶ୍ୟକ',
        'validationNumeric': 'ଦୟାକରି ଏକ ବୈଧ ସଂଖ୍ୟା ପ୍ରବେଶ କରନ୍ତୁ',
        'edit': 'ସମ୍ପାଦନ କରନ୍ତୁ',
        'marketplace': 'ମାର୍କେଟପ୍ଲେସ୍',
        'search': 'ସନ୍ଧାନ କରନ୍ତୁ',
        'nearbyProducts': 'ନିକଟବର୍ତ୍ତୀ ଉତ୍ପାଦଗୁଡିକ',
        'all': 'ସମସ୍ତ',
        'farmerId': 'କୃଷକ ଆଇଡି',
        'sort': 'ସଜାଡନ୍ତୁ',
        'priceLowToHigh': 'ମୂଲ୍ୟ: କମ୍ ରୁ ଅଧିକ',
        'priceHighToLow': 'ମୂଲ୍ୟ: ଅଧିକ ରୁ କମ୍',
        'nearest': 'ନିକଟତମ',
        'noProductsFound': 'କୌଣସି ଉତ୍ପାଦ ମିଳିଲା ନାହିଁ',
        'clear': 'ସଫା କରନ୍ତୁ',
        'viewDetails': 'ବିବରଣୀ ଦେଖନ୍ତୁ',
        'compare': 'ତୁଳନା କରନ୍ତୁ',
        'comingSoon': 'ଖୁବ୍ ଶୀଘ୍ର ଆସୁଛି',
        'buyNow': 'ବର୍ତ୍ତମାନ କିଣନ୍ତୁ (ଖୁବ୍ ଶୀଘ୍ର ଆସୁଛି)',
        'myCart': 'ମୋର କାର୍ଟ',
        'addToCart': 'କାର୍ଟରେ ଯୋଡନ୍ତୁ',
        'addedToCart': 'କାର୍ଟରେ ଯୋଡାଯାଇଛି',
        'remove': 'କାଢନ୍ତୁ',
        'subtotal': 'ସବଟୋଟାଲ୍',
        'total': 'ମୋଟ',
        'grandTotal': 'ସର୍ବମୋଟ',
        'checkout': 'ଚେକ୍ଆଉଟ୍',
        'orderSummary': 'ଅର୍ଡର ସାରାଂଶ',
        'placeOrder': 'ଅର୍ଡର କରନ୍ତୁ',
        'orderPlaced': 'ଅର୍ଡର ସଫଳତାର ସହ କରାଯାଇଛି',
        'orderId': 'ଅର୍ଡର ଆଇଡି',
        'orderDetails': 'ଅର୍ଡର ବିବରଣୀ',
        'placed': 'କରାଯାଇଛି',
        'preparing': 'ପ୍ରସ୍ତୁତ ହେଉଛି',
        'readyForPickup': 'ପିକଅପ୍ ପାଇଁ ପ୍ରସ୍ତୁତ',
        'completed': 'ସମ୍ପୂର୍ଣ୍ଣ',
        'cancelled': 'ବାତିଲ୍ କରାଯାଇଛି',
        'cancelOrder': 'ଅର୍ଡର ବାତିଲ୍ କରନ୍ତୁ',
        'confirmCancellation': 'ଆପଣ ନିଶ୍ଚିତ କି ଆପଣ ଏହି ଅର୍ଡର ବାତିଲ୍ କରିବାକୁ ଚାହୁଁଛନ୍ତି?',
        'continueShopping': 'କିଣାକିଣି ଜାରି ରଖନ୍ତୁ',
        'viewMyOrders': 'ମୋର ଅର୍ଡର ଦେଖନ୍ତୁ',
        'deliveryLocation': 'ଡେଲିଭରୀ ସ୍ଥାନ',
        'paymentIntegrationComingSoon': 'ପେମେଣ୍ଟ ଇଣ୍ଟିଗ୍ରେସନ୍ ଖୁବ୍ ଶୀଘ୍ର ଆସୁଛି',
        'emptyCart': 'ଆପଣଙ୍କ କାର୍ଟ ଖାଲି ଅଛି',
        'noOrders': 'କୌଣସି ଅର୍ଡର ମିଳିଲା ନାହିଁ',
        'status': 'ସ୍ଥିତି',
        'date': 'ତାରିଖ',
        'items': 'ଆଇଟମ୍ ଗୁଡିକ',
        'farmerOrders': 'କୃଷକ ଅର୍ଡର',
        'updateStatus': 'ସ୍ଥିତି ଅପଡେଟ୍ କରନ୍ତୁ',
        'myRequirements': 'ମୋର ଆବଶ୍ୟକତା',
        'createRequirement': 'ଆବଶ୍ୟକତା ସୃଷ୍ଟି କରନ୍ତୁ',
        'product': 'ଉତ୍ପାଦ',
        'requiredQuantity': 'ଆବଶ୍ୟକ ପରିମାଣ',
        'targetPrice': 'ଲକ୍ଷ୍ୟ ମୂଲ୍ୟ',
        'requiredBy': 'ଆବଶ୍ୟକ',
        'offers': 'ଅଫର୍ ଗୁଡିକ',
        'viewOffers': 'ଅଫର୍ ଗୁଡିକ ଦେଖନ୍ତୁ',
        'submitOffer': 'ଅଫର୍ ଦାଖଲ କରନ୍ତୁ',
        'availableQuantity': 'ଉପଲବ୍ଧ ପରିମାଣ',
        'offeredPrice': 'ଅଫର୍ ମୂଲ୍ୟ',
        'readyDate': 'ପ୍ରସ୍ତୁତ ତାରିଖ',
        'farmerNote': 'କୃଷକ ନୋଟ୍',
        'acceptOffer': 'ଅଫର୍ ଗ୍ରହଣ କରନ୍ତୁ',
        'rejectOffer': 'ଅଫର୍ ପ୍ରତ୍ୟାଖ୍ୟାନ କରନ୍ତୁ',
        'withdrawOffer': 'ଅଫର୍ ପ୍ରତ୍ୟାହାର କରନ୍ତୁ',
        'remainingQuantity': 'ବଳକା ପରିମାଣ',
        'expired': 'ସମାପ୍ତ',
        'shortlisted': 'ସର୍ଟଲିଷ୍ଟ କରାଯାଇଛି',
        'bestQuality': 'ସର୍ବୋତ୍ତମ ଗୁଣବତ୍ତା',
        'earliestReadyDate': 'ପ୍ରାରମ୍ଭିକ ପ୍ରସ୍ତୁତ ତାରିଖ',
        'noRequirements': 'କୌଣସି ଆବଶ୍ୟକତା ମିଳିଲା ନାହିଁ',
        'noOffers': 'କୌଣସି ଅଫର୍ ମିଳିଲା ନାହିଁ',
        'target': 'ଲକ୍ଷ୍ୟ',
        'publish': 'ପ୍ରକାଶ କରନ୍ତୁ',
        'compareOffers': 'ଅଫର୍ ତୁଳନା କରନ୍ତୁ',
        'buyer': 'କ୍ରେତା'
    },
    'pa': {
        'validationRequired': 'ਇਹ ਖੇਤਰ ਲੋੜੀਂਦਾ ਹੈ',
        'validationNumeric': 'ਕਿਰਪਾ ਕਰਕੇ ਇੱਕ ਵੈਧ ਸੰਖਿਆ ਦਾਖਲ ਕਰੋ',
        'edit': 'ਸੰਪਾਦਨ ਕਰੋ',
        'marketplace': 'ਮਾਰਕੀਟਪਲੇਸ',
        'search': 'ਖੋਜ',
        'nearbyProducts': 'ਨੇੜਲੇ ਉਤਪਾਦ',
        'all': 'ਸਾਰੇ',
        'farmerId': 'ਕਿਸਾਨ ਆਈਡੀ',
        'sort': 'ਤਰਤੀਬ ਦਿਓ',
        'priceLowToHigh': 'ਕੀਮਤ: ਘੱਟ ਤੋਂ ਵੱਧ',
        'priceHighToLow': 'ਕੀਮਤ: ਵੱਧ ਤੋਂ ਘੱਟ',
        'nearest': 'ਨੇੜਲਾ',
        'noProductsFound': 'ਕੋਈ ਉਤਪਾਦ ਨਹੀਂ ਮਿਲਿਆ',
        'clear': 'ਸਾਫ਼ ਕਰੋ',
        'viewDetails': 'ਵੇਰਵੇ ਦੇਖੋ',
        'compare': 'ਤੁਲਨਾ ਕਰੋ',
        'comingSoon': 'ਜਲਦੀ ਆ ਰਿਹਾ ਹੈ',
        'buyNow': 'ਹੁਣੇ ਖਰੀਦੋ (ਜਲਦੀ ਆ ਰਿਹਾ ਹੈ)',
        'myCart': 'ਮੇਰਾ ਕਾਰਟ',
        'addToCart': 'ਕਾਰਟ ਵਿੱਚ ਸ਼ਾਮਲ ਕਰੋ',
        'addedToCart': 'ਕਾਰਟ ਵਿੱਚ ਸ਼ਾਮਲ ਕੀਤਾ ਗਿਆ',
        'remove': 'ਹਟਾਓ',
        'subtotal': 'ਉਪ-ਕੁੱਲ',
        'total': 'ਕੁੱਲ',
        'grandTotal': 'ਮਹਾ ਕੁੱਲ',
        'checkout': 'ਚੈੱਕਆਉਟ',
        'orderSummary': 'ਆਰਡਰ ਸੰਖੇਪ',
        'placeOrder': 'ਆਰਡਰ ਦਿਓ',
        'orderPlaced': 'ਆਰਡਰ ਸਫਲਤਾਪੂਰਵਕ ਦਿੱਤਾ ਗਿਆ',
        'orderId': 'ਆਰਡਰ ਆਈਡੀ',
        'orderDetails': 'ਆਰਡਰ ਵੇਰਵੇ',
        'placed': 'ਦਿੱਤਾ ਗਿਆ',
        'preparing': 'ਤਿਆਰ ਹੋ ਰਿਹਾ ਹੈ',
        'readyForPickup': 'ਪਿਕਅੱਪ ਲਈ ਤਿਆਰ',
        'completed': 'ਪੂਰਾ ਹੋਇਆ',
        'cancelled': 'ਰੱਦ ਕੀਤਾ ਗਿਆ',
        'cancelOrder': 'ਆਰਡਰ ਰੱਦ ਕਰੋ',
        'confirmCancellation': 'ਕੀ ਤੁਸੀਂ ਯਕੀਨੀ ਤੌਰ ਤੇ ਇਸ ਆਰਡਰ ਨੂੰ ਰੱਦ ਕਰਨਾ ਚਾਹੁੰਦੇ ਹੋ?',
        'continueShopping': 'ਖਰੀਦਦਾਰੀ ਜਾਰੀ ਰੱਖੋ',
        'viewMyOrders': 'ਮੇਰੇ ਆਰਡਰ ਦੇਖੋ',
        'deliveryLocation': 'ਡਿਲੀਵਰੀ ਸਥਾਨ',
        'paymentIntegrationComingSoon': 'ਭੁਗਤਾਨ ਏਕੀਕਰਣ ਜਲਦੀ ਆ ਰਿਹਾ ਹੈ',
        'emptyCart': 'ਤੁਹਾਡਾ ਕਾਰਟ ਖਾਲੀ ਹੈ',
        'noOrders': 'ਕੋਈ ਆਰਡਰ ਨਹੀਂ ਮਿਲਿਆ',
        'status': 'ਸਥਿਤੀ',
        'date': 'ਮਿਤੀ',
        'items': 'ਆਈਟਮਾਂ',
        'farmerOrders': 'ਕਿਸਾਨ ਆਰਡਰ',
        'updateStatus': 'ਸਥਿਤੀ ਅੱਪਡੇਟ ਕਰੋ',
        'myRequirements': 'ਮੇਰੀਆਂ ਲੋੜਾਂ',
        'createRequirement': 'ਲੋੜ ਬਣਾਓ',
        'product': 'ਉਤਪਾਕ',
        'requiredQuantity': 'ਲੋੜੀਂਦੀ ਮਾਤਰਾ',
        'targetPrice': 'ਟੀਚਾ ਕੀਮਤ',
        'requiredBy': 'ਦੁਆਰਾ ਲੋੜੀਂਦਾ',
        'offers': 'ਪੇਸ਼ਕਸ਼ਾਂ',
        'viewOffers': 'ਪੇਸ਼ਕਸ਼ਾਂ ਦੇਖੋ',
        'submitOffer': 'ਪੇਸ਼ਕਸ਼ ਜਮ੍ਹਾ ਕਰੋ',
        'availableQuantity': 'ਉਪਲਬਧ ਮਾਤਰਾ',
        'offeredPrice': 'ਪੇਸ਼ਕਸ਼ ਕੀਮਤ',
        'readyDate': 'ਤਿਆਰ ਮਿਤੀ',
        'farmerNote': 'ਕਿਸਾਨ ਨੋਟ',
        'acceptOffer': 'ਪੇਸ਼ਕਸ਼ ਸਵੀਕਾਰ ਕਰੋ',
        'rejectOffer': 'ਪੇਸ਼ਕਸ਼ ਰੱਦ ਕਰੋ',
        'withdrawOffer': 'ਪੇਸ਼ਕਸ਼ ਵਾਪਸ ਲਓ',
        'remainingQuantity': 'ਬਾਕੀ ਮਾਤਰਾ',
        'expired': 'ਮਿਆਦ ਪੁੱਗ ਗਈ',
        'shortlisted': 'ਸ਼ਾਰਟਲਿਸਟ ਕੀਤਾ ਗਿਆ',
        'bestQuality': 'ਵਧੀਆ ਗੁਣਵੱਤਾ',
        'earliestReadyDate': 'ਸਭ ਤੋਂ ਪਹਿਲਾਂ ਤਿਆਰ ਮਿਤੀ',
        'noRequirements': 'ਕੋਈ ਲੋੜਾਂ ਨਹੀਂ ਮਿਲੀਆਂ',
        'noOffers': 'ਕੋਈ ਪੇਸ਼ਕਸ਼ਾਂ ਨਹੀਂ ਮਿਲੀਆਂ',
        'target': 'ਟੀਚਾ',
        'publish': 'ਪ੍ਰਕਾਸ਼ਿਤ ਕਰੋ',
        'compareOffers': 'ਪੇਸ਼ਕਸ਼ਾਂ ਦੀ ਤੁਲਨਾ ਕਰੋ',
        'buyer': 'ਖਰੀਦਦਾਰ'
    },
    'as': {
        'validationRequired': 'এই ক্ষেত্ৰখন প্ৰয়োজনীয়',
        'validationNumeric': 'অনুগ্ৰহ কৰি এটা বৈধ সংখ্যা লিখক',
        'edit': 'সম্পাদনা কৰক',
        'marketplace': 'বজাৰ',
        'search': 'সন্ধান কৰক',
        'nearbyProducts': 'ওচৰৰ সামগ্ৰীসমূহ',
        'all': 'সকলো',
        'farmerId': 'কৃষক আইডি',
        'sort': 'সজাওক',
        'priceLowToHigh': 'দাম: কমৰ পৰা বেছি',
        'priceHighToLow': 'দাম: বেছিৰ পৰা কম',
        'nearest': 'নিকটতম',
        'noProductsFound': 'কোনো সামগ্ৰী পোৱা নগ’ল',
        'clear': 'মচি পেলাওক',
        'viewDetails': 'বিৱৰণ চাওক',
        'compare': 'তুলনা কৰক',
        'comingSoon': 'অতি শীঘ্ৰে আহি আছে',
        'buyNow': 'এতিয়া কিনক (অতি শীঘ্ৰে আহি আছে)',
        'myCart': 'মোৰ কাৰ্ট',
        'addToCart': 'কাৰ্টত যোগ কৰক',
        'addedToCart': 'কাৰ্টত যোগ কৰা হৈছে',
        'remove': 'আঁতৰাওক',
        'subtotal': 'উপমুঠ',
        'total': 'মুঠ',
        'grandTotal': 'সৰ্বমুঠ',
        'checkout': 'চেকআউট',
        'orderSummary': 'অৰ্ডাৰৰ সাৰাংশ',
        'placeOrder': 'অৰ্ডাৰ কৰক',
        'orderPlaced': 'সফলতাৰে অৰ্ডাৰ কৰা হৈছে',
        'orderId': 'অৰ্ডাৰ আইডি',
        'orderDetails': 'অৰ্ডাৰৰ বিৱৰণ',
        'placed': 'কৰা হৈছে',
        'preparing': 'প্ৰস্তুত কৰা হৈছে',
        'readyForPickup': 'পিকআপৰ বাবে প্ৰস্তুত',
        'completed': 'সম্পূৰ্ণ',
        'cancelled': 'বাতিল কৰা হৈছে',
        'cancelOrder': 'অৰ্ডাৰ বাতিল কৰক',
        'confirmCancellation': 'আপুনি নিশ্চিতনে যে আপুনি এই অৰ্ডাৰ বাতিল কৰিব বিচাৰে?',
        'continueShopping': 'বজাৰ কৰা চলাই থাকক',
        'viewMyOrders': 'মোৰ অৰ্ডাৰসমূহ চাওক',
        'deliveryLocation': 'ডেলিভাৰীৰ স্থান',
        'paymentIntegrationComingSoon': 'পেমেন্ট ইন্টিগ্ৰেচন অতি শীঘ্ৰে আহি আছে',
        'emptyCart': 'আপোনাৰ কাৰ্ট খালী',
        'noOrders': 'কোনো অৰ্ডাৰ পোৱা নগ’ল',
        'status': 'স্থিতি',
        'date': 'তাৰিখ',
        'items': 'আইটেমসমূহ',
        'farmerOrders': 'কৃষকৰ অৰ্ডাৰ',
        'updateStatus': 'স্থিতি আপডেট কৰক',
        'myRequirements': 'মোৰ প্ৰয়োজনীয়তাসমূহ',
        'createRequirement': 'প্ৰয়োজনীয়তা সৃষ্টি কৰক',
        'product': 'সামগ্ৰী',
        'requiredQuantity': 'প্ৰয়োজনীয় পৰিমাণ',
        'targetPrice': 'লক্ষ্য দাম',
        'requiredBy': 'প্ৰয়োজন',
        'offers': 'প্ৰস্তাৱসমূহ',
        'viewOffers': 'প্ৰস্তাৱসমূহ চাওক',
        'submitOffer': 'প্ৰস্তাৱ দাখিল কৰক',
        'availableQuantity': 'উপলব্ধ পৰিমাণ',
        'offeredPrice': 'প্ৰস্তাৱিত দাম',
        'readyDate': 'প্ৰস্তুত তাৰিখ',
        'farmerNote': 'কৃষকৰ টোকা',
        'acceptOffer': 'প্ৰস্তাৱ গ্ৰহণ কৰক',
        'rejectOffer': 'প্ৰস্তাৱ প্ৰত্যাখ্যান কৰক',
        'withdrawOffer': 'প্ৰস্তাৱ প্ৰত্যাহাৰ কৰক',
        'remainingQuantity': 'অৱশিষ্ট পৰিমাণ',
        'expired': 'ম্যাদ উকলিছে',
        'shortlisted': 'বাচনি কৰা হৈছে',
        'bestQuality': 'শ্ৰেষ্ঠ মানদণ্ড',
        'earliestReadyDate': 'আটাইতকৈ সোনকালে প্ৰস্তুত তাৰিখ',
        'noRequirements': 'কোনো প্ৰয়োজনীয়তা পোৱা নগ’ল',
        'noOffers': 'কোনো প্ৰস্তাৱ পোৱা নগ’ল',
        'target': 'লক্ষ্য',
        'publish': 'প্ৰকাশ কৰক',
        'compareOffers': 'প্ৰস্তাৱসমূহ তুলনা কৰক',
        'buyer': 'ক্ৰেতা'
    }
}

l10n_dir = r'C:\Users\Public\Documents\coding\KrishiMarket\lib\l10n'
for lang in langs:
    file_path = os.path.join(l10n_dir, f'app_{lang}.arb')
    if os.path.exists(file_path):
        with open(file_path, 'r', encoding='utf-8') as f:
            data = json.load(f)
            
        # Update the short dict fields
        for k, v in translations.items():
            if lang in v:
                data[k] = v[lang]
                
        # Update the extended dict fields
        for k, v in extended_translations[lang].items():
            data[k] = v
            
        with open(file_path, 'w', encoding='utf-8') as f:
            json.dump(data, f, ensure_ascii=False, indent=2)
        print(f"Updated app_{lang}.arb")
