import 'dart:convert';
import 'dart:io';

void main() {
  final newKeys = {
    'en': {
      'phoneAuthTitle': 'Sign In',
      'phoneAuthSubtitle': 'Enter your phone number to continue',
      'phoneNumberHint': '10-digit mobile number',
      'continueBtn': 'Continue',
      'termsAccept': 'By continuing, you accept our Terms and Privacy Policy',
      'invalidPhone': 'Invalid phone number',
      'otpTitle': 'Verify OTP',
      'otpSubtitle': 'Enter the 6-digit code sent to your phone',
      'resendOtp': 'Resend OTP',
      'verifyBtn': 'Verify',
      'invalidOtp': 'Invalid OTP',
      'otpExpired': 'OTP Expired',
      'tooManyAttempts': 'Too many attempts. Try again later.',
      'profileTitle': 'Complete Profile',
      'fullNameHint': 'Full Name',
      'locationHint': 'Location (Village/City)',
      'businessNameHint': 'Business Name',
      'businessTypeHint': 'Business Type',
      'restaurant': 'Restaurant',
      'hotel': 'Hotel',
      'groceryStore': 'Grocery Store',
      'other': 'Other',
      'logout': 'Logout',
      'save': 'Save',
      'networkError': 'Network Error',
      'unknownError': 'An unknown error occurred',
    },
    'hi': {
      'phoneAuthTitle': 'साइन इन करें',
      'phoneAuthSubtitle': 'आगे बढ़ने के लिए अपना फोन नंबर दर्ज करें',
      'phoneNumberHint': '10-अंकों का मोबाइल नंबर',
      'continueBtn': 'आगे बढ़ें',
      'termsAccept':
          'आगे बढ़कर, आप हमारी शर्तों और गोपनीयता नीति को स्वीकार करते हैं',
      'invalidPhone': 'अमान्य फोन नंबर',
      'otpTitle': 'OTP सत्यापित करें',
      'otpSubtitle': 'आपके फोन पर भेजा गया 6-अंकीय कोड दर्ज करें',
      'resendOtp': 'OTP पुनः भेजें',
      'verifyBtn': 'सत्यापित करें',
      'invalidOtp': 'अमान्य OTP',
      'otpExpired': 'OTP समाप्त हो गया',
      'tooManyAttempts': 'बहुत सारे प्रयास। बाद में पुनः प्रयास करें।',
      'profileTitle': 'प्रोफ़ाइल पूरी करें',
      'fullNameHint': 'पूरा नाम',
      'locationHint': 'स्थान (गाँव/शहर)',
      'businessNameHint': 'व्यवसाय का नाम',
      'businessTypeHint': 'व्यवसाय का प्रकार',
      'restaurant': 'रेस्टोरेंट',
      'hotel': 'होटल',
      'groceryStore': 'किराने की दुकान',
      'other': 'अन्य',
      'logout': 'लॉग आउट',
      'save': 'सहेजें',
      'networkError': 'नेटवर्क त्रुटि',
      'unknownError': 'एक अज्ञात त्रुटि हुई',
    },
    'bn': {
      'phoneAuthTitle': 'সাইন ইন',
      'phoneAuthSubtitle': 'এগিয়ে যেতে আপনার ফোন নম্বর লিখুন',
      'phoneNumberHint': '১০-সংখ্যার মোবাইল নম্বর',
      'continueBtn': 'এগিয়ে যান',
      'termsAccept': 'চালিয়ে যাওয়ার মাধ্যমে, আপনি আমাদের শর্তাবলী এবং গোপনীয়তা নীতি গ্রহণ করেন',
      'invalidPhone': 'অবৈধ ফোন নম্বর',
      'otpTitle': 'OTP যাচাই করুন',
      'otpSubtitle': 'আপনার ফোনে প্রেরিত ৬-সংখ্যার কোডটি লিখুন',
      'resendOtp': 'OTP পুনরায় পাঠান',
      'verifyBtn': 'যাচাই করুন',
      'invalidOtp': 'অবৈধ OTP',
      'otpExpired': 'OTP মেয়াদোত্তীর্ণ',
      'tooManyAttempts': 'অনেক বেশি চেষ্টা করা হয়েছে। পরে আবার চেষ্টা করুন।',
      'profileTitle': 'প্রোফাইল সম্পূর্ণ করুন',
      'fullNameHint': 'পুরো নাম',
      'locationHint': 'অবস্থান (গ্রাম/শহর)',
      'businessNameHint': 'ব্যবসার নাম',
      'businessTypeHint': 'ব্যবসার ধরন',
      'restaurant': 'রেস্তোরাঁ',
      'hotel': 'হোটেল',
      'groceryStore': 'মুদির দোকান',
      'other': 'অন্যান্য',
      'logout': 'লগ আউট',
      'save': 'সংরক্ষণ করুন',
      'networkError': 'নেটওয়ার্ক ত্রুটি',
      'unknownError': 'একটি অজানা ত্রুটি ঘটেছে',
    },
    'mr': {
      'phoneAuthTitle': 'साइन इन करा',
      'phoneAuthSubtitle': 'पुढे जाण्यासाठी तुमचा फोन नंबर एंटर करा',
      'phoneNumberHint': '10-अंकी मोबाइल नंबर',
      'continueBtn': 'पुढे जा',
      'termsAccept':
          'पुढे जाण्याने, तुम्ही आमच्या अटी आणि गोपनीयता धोरणाचा स्वीकार करता',
      'invalidPhone': 'अवैध फोन नंबर',
      'otpTitle': 'OTP सत्यापित करा',
      'otpSubtitle': 'तुमच्या फोनवर पाठवलेला 6-अंकी कोड एंटर करा',
      'resendOtp': 'OTP पुन्हा पाठवा',
      'verifyBtn': 'सत्यापित करा',
      'invalidOtp': 'अवैध OTP',
      'otpExpired': 'OTP कालबाह्य',
      'tooManyAttempts': 'खूप प्रयत्न केले. नंतर पुन्हा प्रयत्न करा.',
      'profileTitle': 'प्रोफाइल पूर्ण करा',
      'fullNameHint': 'पूर्ण नाव',
      'locationHint': 'स्थान (गाव/शहर)',
      'businessNameHint': 'व्यवसायाचे नाव',
      'businessTypeHint': 'व्यवसायाचा प्रकार',
      'restaurant': 'रेस्टॉरंट',
      'hotel': 'हॉटेल',
      'groceryStore': 'किराणा दुकान',
      'other': 'इतर',
      'logout': 'लॉग आउट',
      'save': 'जतन करा',
      'networkError': 'नेटवर्क त्रुटी',
      'unknownError': 'अज्ञात त्रुटी आढळली',
    },
    'te': {
      'phoneAuthTitle': 'సైన్ ఇన్ చేయండి',
      'phoneAuthSubtitle': 'కొనసాగించడానికి మీ ఫోన్ నంబర్‌ను నమోదు చేయండి',
      'phoneNumberHint': '10-అంకెల మొబైల్ నంబర్',
      'continueBtn': 'కొనసాగించండి',
      'termsAccept': 'కొనసాగించడం ద్వారా, మీరు మా నిబంధనలు మరియు గోప్యతా విధానాన్ని అంగీకరిస్తున్నారు',
      'invalidPhone': 'చెల్లని ఫోన్ నంబర్',
      'otpTitle': 'OTP ని ధృవీకరించండి',
      'otpSubtitle': 'మీ ఫోన్‌కు పంపిన 6-అంకెల కోడ్‌ను నమోదు చేయండి',
      'resendOtp': 'OTP ని మళ్లీ పంపండి',
      'verifyBtn': 'ధృవీకరించండి',
      'invalidOtp': 'చెల్లని OTP',
      'otpExpired': 'OTP గడువు ముగిసింది',
      'tooManyAttempts': 'చాలా ప్రయత్నాలు. తర్వాత మళ్ళీ ప్రయత్నించండి.',
      'profileTitle': 'ప్రొఫైల్‌ను పూర్తి చేయండి',
      'fullNameHint': 'పూర్తి పేరు',
      'locationHint': 'స్థానం (గ్రామం/నగరం)',
      'businessNameHint': 'వ్యాపారం పేరు',
      'businessTypeHint': 'వ్యాపారం రకం',
      'restaurant': 'రెస్టారెంట్',
      'hotel': 'హోటల్',
      'groceryStore': 'కిరాణా దుకాణం',
      'other': 'ఇతర',
      'logout': 'లాగ్ అవుట్',
      'save': 'సేవ్ చేయండి',
      'networkError': 'నెట్‌వర్క్ లోపం',
      'unknownError': 'తెలియని లోపం ఏర్పడింది',
    },
    'ta': {
      'phoneAuthTitle': 'உள்நுழைக',
      'phoneAuthSubtitle': 'தொடர உங்கள் தொலைபேசி எண்ணை உள்ளிடவும்',
      'phoneNumberHint': '10 இலக்க மொபைல் எண்',
      'continueBtn': 'தொடர்க',
      'termsAccept': 'தொடர்வதன் மூலம், எங்கள் விதிமுறைகள் மற்றும் தனியுரிமை கொள்கையை ஏற்கிறீர்கள்',
      'invalidPhone': 'தவறான தொலைபேசி எண்',
      'otpTitle': 'OTP ஐ சரிபார்க்கவும்',
      'otpSubtitle':
          'உங்கள் தொலைபேசிக்கு அனுப்பப்பட்ட 6 இலக்க குறியீட்டை உள்ளிடவும்',
      'resendOtp': 'OTP ஐ மீண்டும் அனுப்பவும்',
      'verifyBtn': 'சரிபார்க்கவும்',
      'invalidOtp': 'தவறான OTP',
      'otpExpired': 'OTP காலாவதியானது',
      'tooManyAttempts':
          'மிக அதிகமான முயற்சிகள். பின்னர் மீண்டும் முயற்சிக்கவும்.',
      'profileTitle': 'சுயவிவரத்தை முடிக்கவும்',
      'fullNameHint': 'முழு பெயர்',
      'locationHint': 'இடம் (கிராமம்/நகரம்)',
      'businessNameHint': 'வணிக பெயர்',
      'businessTypeHint': 'வணிக வகை',
      'restaurant': 'உணவகம்',
      'hotel': 'விடுதி',
      'groceryStore': 'மளிகை கடை',
      'other': 'மற்றவை',
      'logout': 'வெளியேறு',
      'save': 'சேமி',
      'networkError': 'நெட்வொர்க் பிழை',
      'unknownError': 'ஒரு அறியப்படாத பிழை ஏற்பட்டது',
    },
    'gu': {
      'phoneAuthTitle': 'સાઇન ઇન',
      'phoneAuthSubtitle': 'આગળ વધવા માટે તમારો ફોન નંબર દાખલ કરો',
      'phoneNumberHint': '10-અંકનો મોબાઇલ નંબર',
      'continueBtn': 'આગળ વધો',
      'termsAccept':
          'આગળ વધીને, તમે અમારી શરતો અને ગોપનીયતા નીતિને સ્વીકારો છો',
      'invalidPhone': 'અમાન્ય ફોન નંબર',
      'otpTitle': 'OTP ચકાસો',
      'otpSubtitle': 'તમારા ફોન પર મોકલેલો 6-અંકનો કોડ દાખલ કરો',
      'resendOtp': 'OTP ફરીથી મોકલો',
      'verifyBtn': 'ચકાસો',
      'invalidOtp': 'અમાન્ય OTP',
      'otpExpired': 'OTP ની મુદત પૂરી થઈ ગઈ',
      'tooManyAttempts': 'ઘણા બધા પ્રયાસો. પછીથી ફરી પ્રયાસ કરો.',
      'profileTitle': 'પ્રોફાઇલ પૂર્ણ કરો',
      'fullNameHint': 'પૂરું નામ',
      'locationHint': 'સ્થાન (ગામ/શહેર)',
      'businessNameHint': 'વ્યવસાયનું નામ',
      'businessTypeHint': 'વ્યવસાયનો પ્રકાર',
      'restaurant': 'રેસ્ટોરન્ટ',
      'hotel': 'હોટલ',
      'groceryStore': 'કરિયાણાની દુકાન',
      'other': 'અન્ય',
      'logout': 'લોગ આઉટ',
      'save': 'સાચવો',
      'networkError': 'નેટવર્ક ભૂલ',
      'unknownError': 'અજ્ઞાત ભૂલ આવી',
    },
    'kn': {
      'phoneAuthTitle': 'ಸೈನ್ ಇನ್',
      'phoneAuthSubtitle': 'ಮುಂದುವರೆಯಲು ನಿಮ್ಮ ಫೋನ್ ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ',
      'phoneNumberHint': '10-ಅಂಕಿಯ ಮೊಬೈಲ್ ಸಂಖ್ಯೆ',
      'continueBtn': 'ಮುಂದುವರೆಯಿರಿ',
      'termsAccept': 'ಮುಂದುವರೆಯುವ ಮೂಲಕ, ನೀವು ನಮ್ಮ ನಿಯಮಗಳು ಮತ್ತು ಗೌಪ್ಯತೆ ನೀತಿಯನ್ನು ಒಪ್ಪಿಕೊಳ್ಳುತ್ತೀರಿ',
      'invalidPhone': 'ಅಮಾನ್ಯ ಫೋನ್ ಸಂಖ್ಯೆ',
      'otpTitle': 'OTP ಪರಿಶೀಲಿಸಿ',
      'otpSubtitle': 'ನಿಮ್ಮ ಫೋನ್‌ಗೆ ಕಳುಹಿಸಲಾದ 6-ಅಂಕಿಯ ಕೋಡ್ ನಮೂದಿಸಿ',
      'resendOtp': 'OTP ಮರುಕಳುಹಿಸಿ',
      'verifyBtn': 'ಪರಿಶೀಲಿಸಿ',
      'invalidOtp': 'ಅಮಾನ್ಯ OTP',
      'otpExpired': 'OTP ಅವಧಿ ಮುಗಿದಿದೆ',
      'tooManyAttempts': 'ಹಲವು ಪ್ರಯತ್ನಗಳು. ನಂತರ ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
      'profileTitle': 'ಪ್ರೊಫೈಲ್ ಪೂರ್ಣಗೊಳಿಸಿ',
      'fullNameHint': 'ಪೂರ್ಣ ಹೆಸರು',
      'locationHint': 'ಸ್ಥಳ (ಹಳ್ಳಿ/ನಗರ)',
      'businessNameHint': 'ವ್ಯಾಪಾರದ ಹೆಸರು',
      'businessTypeHint': 'ವ್ಯಾಪಾರದ ಪ್ರಕಾರ',
      'restaurant': 'ರೆಸ್ಟೋರೆಂಟ್',
      'hotel': 'ಹೋಟೆಲ್',
      'groceryStore': 'ದಿನಸಿ ಅಂಗಡಿ',
      'other': 'ಇತರೆ',
      'logout': 'ಲಾಗ್ ಔಟ್',
      'save': 'ಉಳಿಸಿ',
      'networkError': 'ನೆಟ್‌ವರ್ಕ್ ದೋಷ',
      'unknownError': 'ಅಜ್ಞಾತ ದೋಷ ಸಂಭವಿಸಿದೆ',
    },
    'ml': {
      'phoneAuthTitle': 'സൈൻ ഇൻ ചെയ്യുക',
      'phoneAuthSubtitle': 'തുടരുന്നതിന് നിങ്ങളുടെ ഫോൺ നമ്പർ നൽകുക',
      'phoneNumberHint': '10 അക്ക മൊബൈൽ നമ്പർ',
      'continueBtn': 'തുടരുക',
      'termsAccept': 'തുടരുന്നതിലൂടെ, ഞങ്ങളുടെ നിബന്ധനകളും സ്വകാര്യതാ നയവും നിങ്ങൾ അംഗീകരിക്കുന്നു',
      'invalidPhone': 'അസാധുവായ ഫോൺ നമ്പർ',
      'otpTitle': 'OTP പരിശോധിച്ചുറപ്പിക്കുക',
      'otpSubtitle': 'നിങ്ങളുടെ ഫോണിലേക്ക് അയച്ച 6 അക്ക കോഡ് നൽകുക',
      'resendOtp': 'OTP വീണ്ടും അയയ്ക്കുക',
      'verifyBtn': 'പരിശോധിച്ചുറപ്പിക്കുക',
      'invalidOtp': 'അസാധുവായ OTP',
      'otpExpired': 'OTP കാലാവധി കഴിഞ്ഞു',
      'tooManyAttempts': 'കൂടുതൽ ശ്രമങ്ങൾ. പിന്നീട് വീണ്ടും ശ്രമിക്കുക.',
      'profileTitle': 'പ്രൊഫൈൽ പൂർത്തിയാക്കുക',
      'fullNameHint': 'പൂർണ്ണ പേര്',
      'locationHint': 'സ്ഥലം (ഗ്രാമം/നഗരം)',
      'businessNameHint': 'ബിസിനസ്സ് പേര്',
      'businessTypeHint': 'ബിസിനസ്സ് തരം',
      'restaurant': 'റെസ്റ്റോറന്റ്',
      'hotel': 'ഹോട്ടൽ',
      'groceryStore': 'പലചരക്ക് കട',
      'other': 'മറ്റുള്ളവ',
      'logout': 'ലോഗ് ഔട്ട്',
      'save': 'സംരക്ഷിക്കുക',
      'networkError': 'നെറ്റ്‌വർക്ക് പിശക്',
      'unknownError': 'ഒരു അജ്ഞാത പിശക് സംഭവിച്ചു',
    },
    'pa': {
      'phoneAuthTitle': 'ਸਾਈਨ ਇਨ',
      'phoneAuthSubtitle': 'ਜਾਰੀ ਰੱਖਣ ਲਈ ਆਪਣਾ ਫ਼ੋਨ ਨੰਬਰ ਦਰਜ ਕਰੋ',
      'phoneNumberHint': '10-ਅੰਕ ਦਾ ਮੋਬਾਈਲ ਨੰਬਰ',
      'continueBtn': 'ਜਾਰੀ ਰੱਖੋ',
      'termsAccept': 'ਜਾਰੀ ਰੱਖ ਕੇ, ਤੁਸੀਂ ਸਾਡੀਆਂ ਸ਼ਰਤਾਂ ਅਤੇ ਗੋਪਨੀਯਤਾ ਨੀਤੀ ਨੂੰ ਸਵੀਕਾਰ ਕਰਦੇ ਹੋ',
      'invalidPhone': 'ਅਵੈਧ ਫ਼ੋਨ ਨੰਬਰ',
      'otpTitle': 'OTP ਦੀ ਪੁਸ਼ਟੀ ਕਰੋ',
      'otpSubtitle': 'ਆਪਣੇ ਫ਼ੋਨ \'ਤੇ ਭੇਜਿਆ 6-ਅੰਕਾਂ ਦਾ ਕੋਡ ਦਰਜ ਕਰੋ',
      'resendOtp': 'OTP ਦੁਬਾਰਾ ਭੇਜੋ',
      'verifyBtn': 'ਪੁਸ਼ਟੀ ਕਰੋ',
      'invalidOtp': 'ਅਵੈਧ OTP',
      'otpExpired': 'OTP ਮਿਆਦ ਪੁੱਗ ਗਈ',
      'tooManyAttempts': 'ਬਹੁਤ ਸਾਰੀਆਂ ਕੋਸ਼ਿਸ਼ਾਂ. ਬਾਅਦ ਵਿੱਚ ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ.',
      'profileTitle': 'ਪ੍ਰੋਫਾਈਲ ਪੂਰਾ ਕਰੋ',
      'fullNameHint': 'ਪੂਰਾ ਨਾਮ',
      'locationHint': 'ਸਥਾਨ (ਪਿੰਡ/ਸ਼ਹਿਰ)',
      'businessNameHint': 'ਕਾਰੋਬਾਰ ਦਾ ਨਾਮ',
      'businessTypeHint': 'ਕਾਰੋਬਾਰ ਦੀ ਕਿਸਮ',
      'restaurant': 'ਰੈਸਟੋਰੈਂਟ',
      'hotel': 'ਹੋਟਲ',
      'groceryStore': 'ਕਿਰਿਆਨੇ ਦੀ ਦੁਕਾਨ',
      'other': 'ਹੋਰ',
      'logout': 'ਲਾਗ ਆਉਟ',
      'save': 'ਸੇਵ ਕਰੋ',
      'networkError': 'ਨੈੱਟਵਰਕ ਗਲਤੀ',
      'unknownError': 'ਇੱਕ ਅਣਜਾਣ ਗਲਤੀ ਆਈ',
    },
    'or': {
      'phoneAuthTitle': 'ସାଇନ୍ ଇନ୍ କରନ୍ତୁ',
      'phoneAuthSubtitle': 'ଆଗକୁ ବଢିବା ପାଇଁ ଆପଣଙ୍କର ଫୋନ୍ ନମ୍ବର ଦିଅନ୍ତୁ',
      'phoneNumberHint': '10-ଅଙ୍କ ବିଶିଷ୍ଟ ମୋବାଇଲ୍ ନମ୍ବର',
      'continueBtn': 'ଆଗକୁ ବଢନ୍ତୁ',
      'termsAccept': 'ଆଗକୁ ବଢିବା ଦ୍ୱାରା, ଆପଣ ଆମର ସର୍ତ୍ତାବଳୀ ଏବଂ ଗୋପନୀୟତା ନୀତି ଗ୍ରହଣ କରନ୍ତି',
      'invalidPhone': 'ଅବୈଧ ଫୋନ୍ ନମ୍ବର',
      'otpTitle': 'OTP ଯାଞ୍ଚ କରନ୍ତୁ',
      'otpSubtitle': 'ଆପଣଙ୍କ ଫୋନ୍ କୁ ପଠାଯାଇଥିବା 6-ଅଙ୍କ ବିଶିଷ୍ଟ କୋଡ୍ ଦିଅନ୍ତୁ',
      'resendOtp': 'OTP ପୁନର୍ବାର ପଠାନ୍ତୁ',
      'verifyBtn': 'ଯାଞ୍ଚ କରନ୍ତୁ',
      'invalidOtp': 'ଅବୈଧ OTP',
      'otpExpired': 'OTP ର ସମୟ ସରିଯାଇଛି',
      'tooManyAttempts': 'ଅତ୍ୟଧିକ ପ୍ରୟାସ | ପରେ ପୁନର୍ବାର ଚେଷ୍ଟା କରନ୍ତୁ |',
      'profileTitle': 'ପ୍ରୋଫାଇଲ୍ ସମ୍ପୂର୍ଣ୍ଣ କରନ୍ତୁ',
      'fullNameHint': 'ପୂରା ନାମ',
      'locationHint': 'ସ୍ଥାନ (ଗ୍ରାମ/ସହର)',
      'businessNameHint': 'ବ୍ୟବସାୟର ନାମ',
      'businessTypeHint': 'ବ୍ୟବସାୟର ପ୍ରକାର',
      'restaurant': 'ରେଷ୍ଟୁରାଣ୍ଟ',
      'hotel': 'ହୋଟେଲ',
      'groceryStore': 'ଗ୍ରୋସରୀ ଷ୍ଟୋର',
      'other': 'ଅନ୍ୟାନ୍ୟ',
      'logout': 'ଲଗ୍ ଆଉଟ୍',
      'save': 'ସେଭ୍ କରନ୍ତୁ',
      'networkError': 'ନେଟୱାର୍କ ତ୍ରୁଟି',
      'unknownError': 'ଏକ ଅଜ୍ଞାତ ତ୍ରୁଟି ଘଟିଛି',
    },
    'as': {
      'phoneAuthTitle': 'ছাইন ইন কৰক',
      'phoneAuthSubtitle': 'আগুৱাই যাবলৈ আপোনাৰ ফোন নম্বৰ দিয়ক',
      'phoneNumberHint': '১০-অংকৰ মবাইল নম্বৰ',
      'continueBtn': 'আগুৱাই যাওক',
      'termsAccept': 'আগুৱাই যোৱাৰ যোগেদি, আপুনি আমাৰ চৰ্তাৱলী আৰু গোপনীয়তা নীতি গ্ৰহণ কৰে',
      'invalidPhone': 'অবৈধ ফোন নম্বৰ',
      'otpTitle': 'OTP সত্যাগ্ৰহণ কৰক',
      'otpSubtitle': 'আপোনাৰ ফোনলৈ পঠোৱা ৬-অংকৰ কোডটো দিয়ক',
      'resendOtp': 'OTP পুনৰ পঠাওক',
      'verifyBtn': 'সত্যাগ্ৰহণ কৰক',
      'invalidOtp': 'অবৈধ OTP',
      'otpExpired': 'OTP ৰ ম্যাদ উকলিছে',
      'tooManyAttempts': 'অত্যাধিক প্ৰয়াস। পিছত পুনৰ চেষ্টা কৰক।',
      'profileTitle': 'প্ৰফাইল সম্পূৰ্ণ কৰক',
      'fullNameHint': 'পূৰা নাম',
      'locationHint': 'স্থান (গাওঁ/চহৰ)',
      'businessNameHint': 'ব্যৱসায়ৰ নাম',
      'businessTypeHint': 'ব্যৱসায়ৰ প্ৰকাৰ',
      'restaurant': 'ৰেষ্টুৰেণ্ট',
      'hotel': 'হোটেল',
      'groceryStore': 'মোদিকান',
      'other': 'অন্যান্য',
      'logout': 'লগ আউট',
      'save': 'ছেভ কৰক',
      'networkError': 'নেটৱৰ্ক ত্ৰুটি',
      'unknownError': 'অজ্ঞাত ত্ৰুটি ঘটিছে',
    },
  };

  for (final entry in newKeys.entries) {
    final file = File('lib/l10n/app_${entry.key}.arb');
    if (file.existsSync()) {
      final content = file.readAsStringSync();
      final Map<String, dynamic> json = jsonDecode(content);
      json.addAll(entry.value as Map<String, dynamic>);
      file.writeAsStringSync(
        '{\n${json.entries.map((e) => '  "${e.key}": "${e.value}"').join(',\n')}\n}\n',
      );
    }
  }
}
